### ISSUE TITLE
Explanation of the types of hangouts one can create

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#10]
An explanation of the types of hangouts one can create: 
* silent hangout / general study motivation hangout where video + mic is muted 
* teaching hangout (hangout creator will be someone who wants to teach) 
* talk through a chapter of a dense programming book or article pair program on a set of coding exercises 
* work on TUTORIAL X at the same time and ask each other questions if they come up (mostly silent, but everyone working on the same material) 
* collaboration project (like codequarters)

**Comment by Luxisapex** [comment]
This is pretty much fixed with "What is a hangout?", right?
