### ISSUE TITLE
Create Hangout Start/End Time (datetime picker behavior)

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/cb-v2-scratch#100]
Currently, when creating a new hangout, the datetime picker logic defaults the **end time** to current time + 1 hour.  The issue is a user is unable to set the **start time** to some time in the future greater than the default *end time*.

<img width="802" alt="screen shot 2016-04-09 at 11 17 27 am" src="https://cloud.githubusercontent.com/assets/1451729/14405485/b9fa130e-fe44-11e5-868b-e5893a44cd17.png">

The user experience here is a little off since the workaround is to *first* select an **end time** some time in the far future before you're allowed to select a **start time** further out.

Recommend we update the logic to default the *end time* to an empty value but require it on submission.

**Comment by sergeant-q** [comment]
@lpatmo  I think we can close this!

**Comment by lpatmo** [comment]
Thanks @sergeant-q!
