### ISSUE TITLE
CSS for hangout status buttons

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#101]
After a button is clicked on, its background should remain filled instead of returning to normal.

![screen shot 2016-04-09 at 6 09 23 pm](https://cloud.githubusercontent.com/assets/4512699/14407452/4c90e100-fe7e-11e5-945d-cd6e06839fae.jpg)

This is a good-for-beginners issue.

**Comment by mankinchi** [comment]
Hi I am working on this one

**Comment by mankinchi** [comment]
https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/226

Please have a look on this pull request

**Comment by abhiii5459** [comment]
Claimed by @mankinchi

**Comment by lpatmo** [comment]
Whoops, forgot to close this issue -- thanks again @mankinchi :)
