### ISSUE TITLE
Create a "help us keep this project alive!" page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#102]
The link to this page is currently at the footer, but the page has not been created yet.

Content to be figured out, but would be nice to at least have the page in routes.js.

**Comment by lpatmo** [comment]
Good for beginners -- someone can figure out how to create a new page.

**Comment by sebbel** [comment]
I'd like to have this exclusively for first-pr people and announce it in both slack and Facebook group. how would that sound to you people? :)

**Comment by lpatmo** [comment]
@sebbel Sounds good.

**Comment by lpatmo** [comment]
New route should be /sponsor.

**Comment by pdotsani** [comment]
Scaffolded a template with some dummy code for the route...
![capture](https://cloud.githubusercontent.com/assets/5272252/15458670/19e19510-2052-11e6-9d20-2070fd178808.png)  

Anything content wise I should include?

**Comment by lpatmo** [comment]
@pdotsani Looks great! We can worry about the content later. Feel free to push up the branch. :)
