### ISSUE TITLE
"Moderator" Status

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#106]
There should be some way to make a user a moderator and give them the ability to edit hangout posts.

This issue is up for discussion.

**Comment by distalx** [comment]
I propose a role based auth system with the following specs.
User roles `normal - moderator - admin`.

**user**
- create-edit-remove, join, report, `hangout`
- create-edit-remove, upvote `learning`
- report another user

**moderator**
- edit-remove reported hangout.
- block-unblock user 

**admin**
- block / unblock user .
- add-remove  `moderator` (role).

**Comment by sergeant-q** [comment]
@distalx @lpatmo what about learnings? do we care about moderating those? 

@distalx does an **admin** inherit the permissions of a **moderator** and is this role able to edit/remove _any_ hangout for any user?

**Comment by distalx** [comment]
@sergeant-q 
-The permission flow will be  **admin** > **moderator** > **user**.
-I believe **moderator** should be able to edit/remove hangout of any user .

**Comment by lpatmo** [comment]
**moderator**
edit-remove reported hangout.
block-unblock user
add moderators (role)

**admin**
block / unblock user .
add-remove moderators (role)
