### ISSUE TITLE
Refactor code for Slack notifications re: created and cloned hangouts

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/cb-v2-scratch#109]
@lpatmo found the bug that when cloning (copying) an existing hangout, a slack notification is not fired off as it does for new normal hangouts.

**Comment by sergeant-q** [comment]
This should be an easy fix.  I will make the updates tonight.

**Comment by lpatmo** [comment]
We're reusing code for `createHangout` and `cloneHangout` in server/api.js.
