### ISSUE TITLE
Fix tab alignment for Home-Logged-In View

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#118]
Left edge is currently misaligned.

![screen shot 2016-05-08 at 5 39 35 pm](https://cloud.githubusercontent.com/assets/13413986/15101395/fcd2f2c0-1543-11e6-8168-84a2a0ef10c8.png)

**Comment by ollikarppinen** [comment]
This seems doable. :)
I could try to tackle this one.

**Comment by lpatmo** [comment]
@ollikarppinen Go ahead! :) Please create a branch for this issue.

**Comment by abhiii5459** [comment]
Claimed  by @ollikarppinen .
