### ISSUE TITLE
Add "About" page

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#12]
An “about” page (or section of the home page?) explaining what the community is about, and some of the top contributors here -- i.e. people who’ve made pull requests, are volunteer moderators on the Slack, have lots of /prowd points, etc.

**Comment by Luxisapex** [comment]
If this is not intended to be dynamic, I guess it would make sense for someone who holds the information to compile it somewhere, perhaps in this comment section. Then an ignorant fool like I could possibly implement it.

**Comment by Luxisapex** [comment]
Wrote something that I think represents us quite well. Some input from other perspectives would be welcome, then I think we can check this off.

**Comment by lpatmo** [comment]
Thanks for starting it, Joel! I revised it a bit in this commit: https://github.com/codebuddiesdotorg/cb-v2-scratch/commit/1701c20ee4968fc4e99544b7d85fb6d28a52c952

**Comment by adachiu** [comment]
Here's a draft of the About page.
Zeplin link: https://zpl.io/Z1Rl08m

![about-1](https://cloud.githubusercontent.com/assets/13413986/13870953/b77a313a-ec9d-11e5-87b0-a0802030994e.jpg)

**Comment by sergeant-q** [comment]
Is the plan to update the **about.html** page to reflect @adachiu 's mockup?

**Comment by lpatmo** [comment]
Yep! :)
