### ISSUE TITLE
Add tooltips hover to user profile icons on /about page that describe contributions

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#125]
We have a lot of user icons on the about page (https://cbv2-staging.herokuapp.com/about). Everyone listed there has contributed to CBV2, but some have done more than others, or contributed different things. For example, @adachiu is the lead designer. @anbuselvan, @distalx, and @sergeant-q all contributed a lot on the code front. @panndawhisperer helped solve a tricky google hangouts API issue. etc.

The idea: if you hover over each of the user avatars, a tooltip will appear with some extra description about what the user contributed, and a link to their twitter or github profile. 

Thoughts?

Edit: http://jsfiddle.net/9P64a/

**Comment by adachiu** [comment]
I like this idea @lpatmo 
It would be useful for new contributors to see as well. For instance, if they wanted to work on an element of the app which someone else had worked on, they can directly contact them for more information.
