### ISSUE TITLE
Mobile view optimization

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#133]
There are alignment and spacing enhancements to do for optimizing the mobile view. The following screenshot is what I see on an iPhone6S

![screen shot 2016-06-27 at 11 52 21 am](https://cloud.githubusercontent.com/assets/13413986/16391829/aead8d62-3c5d-11e6-89d3-7de2132042e4.png)

**Comment by wuworkshop** [comment]
@lpatmo Might be a good idea to sign up with Sauce Labs Open Sauce plan (it's a free plan for OSS projects) - http://saucelabs.com/opensauce/

**Comment by lpatmo** [comment]
@wuworkshop Is opensauce similar to codeship?

**Comment by wuworkshop** [comment]
@lpatmo I think that depends on the Sauce Labs feature. From the Sauce Labs' site, their Open Sauce plan provides this:

> You’ll automatically be enrolled in the plan, which provides unlimited testing minutes on up to five parallel VMs and access to all our features, including 700+ OS/browser combos, screenshots, debugging tools and more. Please note that using Open Sauce means your tests and results are open to the public.

I was thinking more about the cross-browser and mobile testing features.

**Comment by lpatmo** [comment]
Just noting here that the homepage CSS issue in the screenshot above was filed and claimed in #237.

**Comment by distalx** [comment]
resolved in #258
