### ISSUE TITLE
Redundant About section in FAQ Page

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#134]
The FAQ page also has an "about" section and it seems redundant when we have a separate full page for "About" already. I suggest we remove the about in FAQ and move the text to the About page.

@lpatmo What do you think?

Also there seems to be a broken image link on the FAQ page.

**Comment by lpatmo** [comment]
> The FAQ page also has an "about" section and it seems redundant when we have a separate full page for "About" already. I suggest we remove the about in FAQ and move the text to the About page.

Good call.

> Also there seems to be a broken image link on the FAQ page.

I think the image on the FAQ page has been fixed.

**Comment by lpatmo** [comment]
Fixed this in an earlier commit.
