### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#135]
These 2 icon images need to be updated with the new CB logo:

https://www.codebuddies.org/images/cb2-180.png
https://www.codebuddies.org/images/cb2-196.png

@adachiu, wanna take this one?

**Comment by adachiu** [comment]
@wuworkshop would love to!

**Comment by lpatmo** [comment]
I updated @adachiu's new logo on the favicon and on the "cancelled hangout" email template in private/email-hangout-alerts.html.

Also added Indian flag to the "about" page.

There might be places where I've missed the old logo.

**Comment by lpatmo** [comment]
Update: @adachiu is doing an A/B test on the logos. 

Though I have my personal biases, we haven't yet made an official final decision on which one to use.

**Comment by lpatmo** [comment]
We have a final logo! It is https://codebuddies.org/images/cb-logo.jpg.
