### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#138]
Forgot to file an issue for the longest time, but for the record, getting this bug from the Google API, which *used* to work:

![screen shot 2016-07-05 at 7 57 22 pm](https://cloud.githubusercontent.com/assets/4512699/16606200/cecc4816-42ea-11e6-8cd2-481163e23d53.jpg)

Will write updates here in the comments.

**Comment by lpatmo** [comment]
@anbuselvan's thoughts:

``` I suspect either a parameter is wrong in the url request.. that leads to a 404.. or we are trying to use PUT instead of POST which means PUT can be used for the existing object to update.. unless an object exists then it'll return 404
```

He found that if we did this in public/app.xml:

```
-            xmlhttp.open("PUT", callbackUrl);
+            xmlhttp.open("POST", callbackUrl);
```

... the error disappears. However, I was not able to replicate.

On a brand new meteor app, that javascript/HTML combination below works:

```
<div class="google-hangout">
            <div class="g-hangout" data-render="createhangout"
            data-initial_apps="[{ app_id : '999356798349', start_data: {{_id}}, 'app_type' : 'LOCAL_APP' }]"></div>
        </div>
```
```
$('head').append('<script src="https://apis.google.com/js/platform.js" async defer></script>');
```

The problem is related to some custom code we have that’s conflicting.

**Comment by sergeant-q** [comment]
Once deployed to production, let's mark this for closure!

**Comment by lpatmo** [comment]
CLOSED!!! Thanks to @sergeant-q!
