### ISSUE TITLE
Meta description change

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#140]
Maybe change the meta description from “We're a community of people learning to code via peer-to-peer Google Hangouts. Learning with others helps us learn faster. The project is free and open-sourced.” to “We're a community learning code via a Slack chatroom, a Facebook Group, and peer-to-peer Google Hangouts. Learning with others helps us learn faster. The project is free, open-sourced, and 100% community-built.”

This is a pretty easy pull request -- I can take or let someone else take.

**Comment by leewaygroups** [comment]
I'll take this as a gentle entry.

**Comment by lpatmo** [comment]
@leewaygroups Thanks! Let me know if you have any questions about how to go about it.

**Comment by leewaygroups** [comment]
@lpatmo Thanks. I pushed to a new branch specific to this case already. 
[here](https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/140#issuecomment-233137985)

Let me know if I did the right thing.

Thanks once again.

**Comment by lpatmo** [comment]
@leewaygroups Looks good! Please create a pull request for it. Thank you!
