### ISSUE TITLE
Update final logo everywhere

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#142]
Final logo: Need to change out the twitter.com/codebuddiesmeet and Slack icons!! (pending @adachiu deciding on a final logo, maybe). 

We need something square for Slack and Twitter.

**Comment by wuworkshop** [comment]
Could probably use the icons @adachiu is working on for issue #135

**Comment by adachiu** [comment]
Will be finalizing this weekend.

**Comment by lpatmo** [comment]
New logo designed by @adachiu: 

![cb-avatar-04](https://cloud.githubusercontent.com/assets/4512699/17093354/9c8106fe-51fd-11e6-9fd3-5af709434bd6.jpg)

**Comment by lpatmo** [comment]
(Updated Slack and Twitter!)

**Comment by lpatmo** [comment]
@adachiu designed a new logo that's compatible everywhere:

![cb-logo](https://cloud.githubusercontent.com/assets/4512699/18159143/3c5153b8-6fdc-11e6-9792-c09480e37af3.jpg)

Have replaced Slack and Twitter; just need to replace on website.

**Comment by sergeant-q** [comment]
Awesome!
