### ISSUE TITLE
Slackbot welcome for new users

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#145]
Set up a slackbot on Slack so that new Slack signups get a link to the website and an explanation about how it works.
- Point them to #introduce-yourself
- Link to http://codebuddies.org and explain that they can schedule a silent, collaborative, or teaching hangout.
- (Anything else?)

I remember seeing a website that offered this feature, so we don't have to code the slackbot ourselves. Have to dig a little to remember the name of the service.

**Comment by lpatmo** [comment]
- Once #todayilearned is integrated with the app, add a mention about this hashtag too!

**Comment by wuworkshop** [comment]
Related issues #13 and #148.

**Comment by wuworkshop** [comment]
Just so there's a record, from the Slack group, the website that offers the custom welcome message feature is https://www.hamsterpad.com/

**Comment by lpatmo** [comment]
This is done! New users are getting a welcome message from Slack.
