### ISSUE TITLE
Give users the ability to leave comments on a hangout post

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#146]
This would be a nice feature to have.

(Hardest part: threading comments??)

**Comment by adachiu** [comment]
I think it would be a nice feature to have. Users may want to add a comment about a resource link that they would like to discuss about during a hangout.

**Comment by anbuselvan** [comment]
+1 it's an excellent feature. Not just during the hangout, whoever joined the hangout, they can immediately initiate or join any conversation to prepare themselves for the hangout and even after to discuss about what they learned.

I've like to work on this feature if everyone else is busy with other issues. Will fix all the other UI issues along with it.

**Comment by lpatmo** [comment]
I think @distalx was interested in working on this feature too, but then he's got the schema issue on his plate too.

**Comment by anbuselvan** [comment]
I'm glad to know it's been in progress already. I will have some time during this weekend, let me see I can fix any other priority issues or just get all the UI issues fixed.

**Comment by distalx** [comment]
Sorry for the slow response .
I haven't started working on this one yet.
@abdulhannanali go ahead, It would be great if you can take this one.

**Comment by lpatmo** [comment]
An idea: let's include a "Today I Learned..." box above the comment thread, so people can post about what they learned/accomplished during the hangout directly on the single post page.
