### ISSUE TITLE
Add link to Code of Conduct

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#153]
Not entirely sure where the link should go, but it would be good to have a link to the [Code of Conduct](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/CODE_OF_CONDUCT.md) on the CB site somewhere that's easy to see.

**Comment by adachiu** [comment]
Either in the About or FAQ page would make sense to have the link.

**Comment by lpatmo** [comment]
Also maybe in the footer.

**Comment by leewaygroups** [comment]
I think it'll be nice to have the link in both About and FAQ. Usually FAQ is link the goto place when people have questions about a project. Also if you just what a quick info About comes handy.

**Comment by leewaygroups** [comment]
I'm thinking of adding this to FAQ
Q: What conducts are expected of a community member towards fellow community members
A: Our Pledge
link to the code of conduct
--------------------------------

What do you think?

**Comment by leewaygroups** [comment]
[Change set](https://github.com/codebuddiesdotorg/cb-v2-scratch/commit/0fce561b825dd3724b8d544071171c114c21f372)
