### ISSUE TITLE
CSS for Hangouts Alerts

### ISSUE THREAD

**Issue by leewaygroups** [codebuddiesdotorg/cb-v2-scratch#158]
![hangoutalert](https://cloud.githubusercontent.com/assets/7301892/17053095/916f3468-502a-11e6-9e43-9aefb791eff8.png)

**Comment by sergeant-q** [comment]
oddly the code shows it has always been this way but I can't recall it being this way! I _think_ I see the problemo.  I'll do a quick test and let you know.

**Comment by lpatmo** [comment]
I just got this email alert, and I think it looks fixed!
