### ISSUE TITLE
Idea: put a snapshot of the description (maybe 50 char. max?) on the homepage for each hangout card

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#170]
There's a lot of white space in each hangout card on the home page. Maybe we should include the first 50 characters of the description in there, so people don't have to click through the title just to read the description, and can preview it.

Good for meteorJS beginners.

**Comment by lpatmo** [comment]
Created a new branch `issue-170-description` for this issue.

**Comment by sgtphips** [comment]
I would like to take a look at this one.

**Comment by lpatmo** [comment]
Since we're going to be turning the events into hangout cards (see https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/203), maybe the description preview could be in a popover? (See: popover effect over the contributor icons on the about page)

**Comment by lpatmo** [comment]
We've created a branch called `s-description-170`. Need to add ellipses to the end of the description text.

Then, let's merge this issue in with the hangouts card issue (#203) so that the description text appears in a popover.

**Comment by ollikarppinen** [comment]
Is this taken? If not I could work on this one

**Comment by lpatmo** [comment]
@ollikarppinen Sorry, the `not-claimed` label was put on here mistakenly. We've created a branch called `s-description-170`.

**Comment by abhiii5459** [comment]
@ollikarppinen Mea culpa!
