### ISSUE TITLE
UI issue: limit description of hangout to 200 characters in Slack notification

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#171]
Whenever a hangout is created, we get a notification in #general.

If the description is too long, the message looks really narrow and lengthy on Slack. We should limit the # of characters in the description in the Slack notification to 200.

See: `lib/functions.js`

**Comment by lpatmo** [comment]
Can do something like `.substr(0,201);` to truncate the text. (see: `s-description-issue-170 branch`)

**Comment by sergeant-q** [comment]
@lpatmo I tested it and it looks great! Do we want to do the same for the hangout subject as well? Not sure how often hangouts are created with really long subjects (title) but we can also truncate it if need be.

**Comment by lpatmo** [comment]
@sergeant-q Good idea; we should also limit the subject line! Maybe to 120 characters or thereabouts.

**Comment by abhiii5459** [comment]
@lpatmo Are you still working on this? Can I take it? 😄

**Comment by lpatmo** [comment]
@abhiii5459 It's yours! I will change the `claimed` label. Thanks!
