### ISSUE TITLE
Emoticon hangout alerts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#180]
If the topic matches a certain keyword (e.g. javascript, laravel, meteor, etc.), the hangout alert in Slack will display an icon matching that keyword.

![screen shot 2016-08-02 at 10 54 03 pm](https://cloud.githubusercontent.com/assets/4512699/17355255/0d9dc572-5904-11e6-84ce-3f4cc15df0bc.jpg)

Certain keywords have more weight over others. For example, javascript > meteor.

**Comment by osanseviero** [comment]
Hey. is anybody still working on this? If not, I could do it.

**Comment by distalx** [comment]
closing this issue - it's not feasible.
