### ISSUE TITLE
Bug: profile page contains list of all hangouts, not individual user's completed hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#182]

**Comment by lpatmo** [comment]
Distalx says: 

> the reason behind of issue #182  is https://github.com/meteor/meteor/issues/4142
meteor does not support `$eq ` operator at this moment - so we are not able to run `{users:{ $elemMatch:{ $eq: userId}}` this query at client side - and we end up displaying all the hangouts

**Comment by William-R-Wilson** [comment]
Thanks, that's helpful!

**Comment by crazcalm** [comment]
Is anyone working on this? I am not sure if I can fix it, but I would like to try :)

**Comment by William-R-Wilson** [comment]
I'm still working on it, slowly but surely.  Might do a hangout next time I work on it if you're interested.

**Comment by crazcalm** [comment]
Okay. Understood. I am not sure if this helps, but in the meteor issue linked above, the comment posted by " udiedrichsen commented on Jun 16, 2015 " has a one line work around for the missing $eq functionality.

**Comment by distalx** [comment]
resolved in #248 .
