### ISSUE TITLE
New error found in google hangout console

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#191]
![screen shot 2016-08-22 at 12 02 04 am](https://cloud.githubusercontent.com/assets/4512699/17843614/0d6ce0a2-67fe-11e6-9f7e-48cf4b483303.jpg)

The errors from #189 and #190 are fixed, but the hangout URL is still not POSTing to the app. Now this is the error message I see when I open up the console in a google hangout launched from the "Start hangout" button on the app.

I'm tempted to revisit http://.appear.in/ again, if only their audio and screensharing quality has improved. They offer an embed, which is nice. Maybe it has since a few months ago?

**Comment by lpatmo** [comment]
Update: Actually, I don't think the error above has anything to do with the problem. On staging, the hangout URL POSTing works and I still see this error message in the console:

![screen shot 2016-08-22 at 12 55 26 am](https://cloud.githubusercontent.com/assets/4512699/17844038/37dbfb84-6803-11e6-9522-98d4b4fbc25c.jpg)

https://cbv2-staging.herokuapp.com/

Maybe the bug here is more recent, since staging is not up-to-date with what's on prod.

**Comment by distalx** [comment]
maybe it's related callback url in app.xml !! ?

**Comment by lpatmo** [comment]
Closing -- @distalx figured out the wrong callback url in app.xml got pushed up (which is why staging's hangout button was miraculously working).
