### ISSUE TITLE
Single post pages: turn links into clickable URLs by adding QuillJS

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#196]
On a post such as https://codebuddies.org/hangout/6rBuM7pG3adGMDBLw, it'd be nice if all the links were clickable.

**Comment by distalx** [comment]
http://quilljs.com/ ?? !

**Comment by lpatmo** [comment]
I started working on this issue in branch `issue-196`.

**Comment by lpatmo** [comment]
Two issues I ran into:

- [ ] Need to figure out how to load `<link href="https://cdn.quilljs.com/1.0.6/quill.snow.css" rel="stylesheet">` and `<script src="https://cdn.quilljs.com/1.0.6/quill.js"></script>` globally on all the meteor pages. Previously was doing 

```Meteor.startup(function() {
    $('head').append('<link href="https://cdn.quilljs.com/1.0.3/quill.snow.css" rel="stylesheet">');
    $('head').append('<script src="https://cdn.quilljs.com/1.0.3/quill.js"></script>');
});
```
in `templates/hangout/hangout.js`, and in each of the other templates. 

I think there's a special way to do this for meteor apps.

- [ ] The description content gets saved as a bunch of raw QuillJS-specific HTML. (You can see it if you control-m and look at data for one of the hangout posts). We need to get the *content* of this data when a user clicks on the "Edit" button to edit the post; otherwise, they'll see a mess of HTML.

**Comment by camilleriluke** [comment]
> Need to figure out how to load <link href="https://cdn.quilljs.com/1.0.6/quill.snow.css" rel="stylesheet"> and <script src="https://cdn.quilljs.com/1.0.6/quill.js"></script> globally on all the meteor pages. Previously was doing

Quill is added as an npm package and everything is sorted (it's just the CSS that needs to be loaded like this)

Some updates from the latest CB sessions

- Data is being save and retrieved well (although it is in it's own format), also it will be taking care of backward compatibility.

- The only issue I am struggling with now is that, when we reply back the description back on the client the links are being prevented from being clicked (seems like a security feature from meteor). I will see how I can get around this.

**Comment by camilleriluke** [comment]
This one is moving a long quite nicely.

Most of the code is ready, just a couple of cleanups and doc, I will be submitting a PR soon ✌️
