### ISSUE TITLE
'About' page: Contributor images not showing

### ISSUE THREAD

**Issue by PandaWhisperer** [codebuddiesdotorg/cb-v2-scratch#199]
I noticed that the contributor images on the about page do not appear to be loading correctly. Only two are shown, with a lot of empty space in between. Additionally, the popovers don't seem to work either.

Using the Web Inspector to investigate, I found a bunch of error messages saying that images weren't loaded due to some "Content Security Policy" that apparently allows external images only from certain sites (see screenshot below). 

<img width="1101" alt="screen shot 2016-09-12 at 6 39 19 pm" src="https://cloud.githubusercontent.com/assets/749244/18444309/efb02c50-7918-11e6-842a-1d7b7f11d1e1.png">

Not sure where this policy comes from and how to fix it.

**Comment by lpatmo** [comment]
@PandaWhisperer I need to deploy the fix to this issue. Thanks for filing!

**Comment by lpatmo** [comment]
This is fixed now!
