### ISSUE TITLE
Improve hangout single page UI (mockup below)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#208]
I played around with a mockup of the single page UI in the browser:

![screen shot 2016-09-21 at 8 18 26 pm](https://cloud.githubusercontent.com/assets/4512699/18736115/d289a4ae-8038-11e6-9896-959b7a68e520.jpg)

Thoughts? 

Improving the look of this page will be helpful to newcomers, IMO.

**Comment by sergeant-q** [comment]
Looks much better. I do have a question regarding the participants.  How would it look like if there's more than three as you have it set up in the mock up?

**Comment by lpatmo** [comment]
@sergeant-q Good question! Maybe we can move it all down to the right...

![screen shot 2016-09-21 at 8 46 07 pm](https://cloud.githubusercontent.com/assets/4512699/18736507/839ff72c-803c-11e6-910c-c868f90e4a71.jpg)

**Comment by lpatmo** [comment]
Merged! (https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/212)
