### ISSUE TITLE
New hangouts created aren't put in the right order

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#220]
I just noticed that a new hangout created on the live site ended up *below* other posts that had already ended. Haven't dug a *lot* into why, but wanted to file this issue to look into later.

![screen shot 2016-09-27 at 6 21 48 pm](https://cloud.githubusercontent.com/assets/4512699/18897491/b729468c-84df-11e6-82bc-0b2b34a84570.jpg)

**Comment by lpatmo** [comment]
Update: I'm not able to replicate this bug in localhost:3000.

**Comment by William-R-Wilson** [comment]
I am seeing this in my local environment.  Just finished my other issue so I'll start on this one

**Comment by lpatmo** [comment]
Great, claimed by @William-R-Wilson!

On the live site, I've noticed that this happens if I duplicate a hangout that was created on an older date.

**Comment by William-R-Wilson** [comment]
I think this is the answer:  https://stackoverflow.com/questions/15153349/meteor-subscribe-doesnt-update-sort-order-of-collection  

Will work on it tonight

**Comment by distalx** [comment]
@William-R-Wilson is this issue has been resolved in PR #272. ?

**Comment by William-R-Wilson** [comment]
Yes! @distalx
