### ISSUE TITLE
Allow hangout creators to end a hangout manually, instead of asking them to input an "end time" in advance

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#221]
A bunch of hangouts scheduled by creators have ended *after* their scheduled time. Creators can get around this by editing the hangout and moving the end time to a couple of minutes later. 

However, having to edit the end time is a little bothersome. It would be nice to have the end time be open-ended, and to be able to hit a button to "End this hangout." 

(Or maybe the end-time open-endedness should be optional?)

If you think this is a good idea, let's discuss the specifics of how this feature should work.

**Comment by sergeant-q** [comment]
@lpatmo I am not entirely certain this issue is **good-for-beginners**.  I like the idea but could be difficult for a beginner to tackle if they're just getting comfortable with the code base. Thoughts?

**Comment by lpatmo** [comment]
@sergeant-q Agreed! I think I mostly added the tag because I was hoping that newcomers would see it and maybe feel compelled to discuss the user experience they'd like to see, but you're right -- might be confusing for this bug to be labelled so. I'll remove.

**Comment by lpatmo** [comment]
Closing this issue -- this is a copy of https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/193.
