### ISSUE TITLE
Inconsistency in hangout's RSVP count.

### ISSUE THREAD

**Issue by leewaygroups** [codebuddiesdotorg/cb-v2-scratch#228]
In all hangouts listing page, the RSVP count for a hangout does not match the actual RSVP counts shown in the hangout's detail page.
![joined 1](https://cloud.githubusercontent.com/assets/7301892/18924704/6cd1d6f6-85db-11e6-9a2b-5d8722ceeca0.png)
![joined 2](https://cloud.githubusercontent.com/assets/7301892/18924734/87ee7066-85db-11e6-9df1-4c25e8737513.png)

**Comment by hi15** [comment]
I'm working on it!

**Comment by adachiu** [comment]
@hi15 is @leewaygroups already working on this? 
I'll label this as `in progress`

**Comment by distalx** [comment]
#246 !!

**Comment by distalx** [comment]
@lpatmo here `joined` count  refers to  number of attendees or attendees + host ?

**Comment by lpatmo** [comment]
Number of attendees + host is fine. Merged.
