### ISSUE TITLE
Update homepage's Slack screenshot with new logo

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#233]
The homepage's Slack screenshot isn't updated yet.

I'm going to update the screenshot.

![screen shot 2016-09-28 at 2 13 27 pm](https://cloud.githubusercontent.com/assets/13413986/18932533/c51997aa-8585-11e6-8235-40de5aa1040a.png)

**Comment by Gouravchawla** [comment]
Hi, Could I make a pull request for this issue? 
This is what I came up with:
![slack-window](https://cloud.githubusercontent.com/assets/2922351/18938885/a3014764-8619-11e6-9305-928e1168a826.png)

**Comment by adachiu** [comment]
@Gouravchawla I already made a PR for this earlier today.

**Comment by Gouravchawla** [comment]
I did not see a PR when I was going through the list of PR. I must have missed it. I'll work on some other issue then.
Thanks!
