### ISSUE TITLE
Add character count to "learnings" tab as well

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#236]
![screen shot 2016-09-29 at 1 43 12 am](https://cloud.githubusercontent.com/assets/4512699/18947019/396d169e-85e6-11e6-8ae3-15fe20207d6d.jpg)

It's not immediately apparent that this learnings/accomplishments box is limited to 140 characters, just like the status box in the first tab.

Would be nice to see a character count next to the left of the Update button.

PR#235 might help: https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/235/commits/40e075ea074cbefba0d3764cafdebd7b80cc92e8

**Comment by camilaavilarinho** [comment]
I'll try this one! :)

**Comment by jmabry111** [comment]
Sorry @camilaavilarinho, I did not see that you commented till just now...

**Comment by camilaavilarinho** [comment]
It's ok, I'll search another one...

**Comment by distalx** [comment]
@jmabry111 Thanks for the PR! :confetti_ball: 
@lpatmo I just noticed that If you copy paste something inside a `I'm working on` or `Today I learned` block it doesn't have any effect on the counter. Dose it qualify as a new issue or it's something that could be addressed here ?

**Comment by lpatmo** [comment]
I left two other notes in PR#243: https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/243.

> Does it qualify as a new issue or it's something that could be addressed here ?

I think either way is fine. If it's not an easy fix, @jmabry111 could create a new issue for it.

**Comment by jmabry111** [comment]
@distalx I fixed the counter to updated if text is pasted in... thanks for the heads up on that!
@lpatmo conflicts are resolved and counter works with no confusion between tabs now.
Thanks! 😀
