### ISSUE TITLE
Make "Get Your Slack Invite" area on home page responsive (HTML/CSS issue)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#237]
![screen shot 2016-09-29 at 12 53 07 am](https://cloud.githubusercontent.com/assets/4512699/18947106/97c40f22-85e6-11e6-817a-2f8e32d1c06b.jpg)

Let's center the Slack signup button + surrounding text.

**Comment by Briix** [comment]
I can get this done 👍

**Comment by christiansafka** [comment]
@Briix Are you working on this, or can I give it a try?

**Comment by adachiu** [comment]
@lpatmo Shall we encourage contributors to `assign` themselves and use the `in-progress` label for issues so we don't have the ongoing questioning of who is working on something?

**Comment by Briix** [comment]
@christiansafka Yes, I am working on it :-) 
If it's okay though, I would like to wait with submitting it until the 1st October (Saturday) so it actually counts towards the hacktober score 😇 

@adachiu @lpatmo I would have loved to do that, but this is my first issue I have "claimed" so I don't know a whole lot about how that actually works or how I would even assign myself to the issue and create the label.

**Comment by camilaavilarinho** [comment]
I'd like to know too how to assign a issue to myself and create a label

**Comment by lpatmo** [comment]
@camilaavilarinho We've stopped using the "assign feature" feature, so now if you want to work on an issue, please just leave a comment in the thread! :) And issues that are already being worked on will have an `in progress` label maintained by repo maintainers. What label did you want to create?

**Comment by distalx** [comment]
resolved in #258.
