### ISSUE TITLE
Adding tooltips for "Interested in" buttons. 

### ISSUE THREAD

**Issue by abhiii5459** [codebuddiesdotorg/cb-v2-scratch#238]
First Issue/PR 😄 
When I first checked out the website, I was confused as to what the buttons meant. I was like, "Can I provide voice input or something?". Then I checked out the FAQs. So I guess tiny tooltips showing the meaning of the buttons would help. 

Working on it.

**Comment by camilleriluke** [comment]
Added some labels for context and assigned you to the issue so it won't be picked up by anyone else :)

**Comment by abhiii5459** [comment]
Thanks @camilleriluke ! :) I've submitted a PR . I had the fix in hand before creating the issue coz I knew it was so obscenely easy, it was bound to be picked up :)

**Comment by camilleriluke** [comment]
It would great to link the PR with the issue to ease navigation between issues and PRs (further reading: https://github.com/blog/957-introducing-issue-mentions)
