### ISSUE TITLE
Duplicate blinking live icon on single post page

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#249]
Spotted an extra `live` icon blinking simultaneously with the main `live` icon. The blinking icon above the join button should be removed.

![screen shot 2016-09-30 at 4 26 03 pm](https://cloud.githubusercontent.com/assets/13413986/19009660/07708f5e-872b-11e6-8fed-04cacb842a98.png)

**Comment by samc1213** [comment]
going to take a look at this

**Comment by raj-maurya** [comment]
@adachiu 

I am interested in fixing this issue.

**Comment by distalx** [comment]
Hi @raj-maurya, I believe @samc1213 is already working on this issue.

**Comment by samc1213** [comment]
You can take it. I can't get the project to run locally. Thanks

**Comment by raj-maurya** [comment]
Thanks @samc1213

**Comment by sergeant-q** [comment]
@adachiu will issue #288 also address this?

**Comment by adachiu** [comment]
@sergeant-q yes, looks like #288 is the same as this issue.

**Comment by wuworkshop** [comment]
@raj-maurya are you still working on this issue? If not, I can change the label back to `not-claimed`.

**Comment by lpatmo** [comment]
Closing (duplicate issue).
