### ISSUE TITLE
Disable Logging in Production.

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/cb-v2-scratch#250]
There are `console log` statements are present in many places. by override the logging functions we can disable logging in production.

**Comment by ollikarppinen** [comment]
I could take this one, if it's up for grabs?

**Comment by lpatmo** [comment]
@ollikarppinen I think @distalx already took this one. Sorry! 

https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/251

**Comment by ollikarppinen** [comment]
Ok, cool. No worries! Just have to find something else then :)
