### ISSUE TITLE
Change "RSVP" to "Launch Now" on button for hangouts in progress

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#257]
![screen shot 2016-10-01 at 10 17 31 am](https://cloud.githubusercontent.com/assets/4512699/19015892/f60847f6-87c1-11e6-82a7-800fb19bd87b.jpg)

For hangouts that are active/in progress, the button on the homepage says "RSVP." It should say "Launch Now", because clicking on the button technically launches the in-progress google hangout.

This button shows up based on this logic in `templates/hangout/hangout-item.html`:
```
            {{#if isInProgress this}}

              {{#if isJoined}}
                {{#if url}}
                  <a class="btn btn-cb2 btn-grey btn-success" href="{{url}}" target="_blank">{{_ "join"}}</a>
                {{else}}
                  {{#unless hangoutOwner host.id}}
                        <p class="status">Please wait for <a href="https://codebuddiesmeet.slack.com/messages/{{getHostId this}}">@{{getHostName this}}</a> to start the hangout.</p>
                      {{/unless}}
                {{/if}}
```
(lines 35-44)

Steps for solving: 
- [ ] Change `<a class="btn btn-cb2 btn-grey btn-success" href="{{url}}" target="_blank">{{_ "join"}}</a>` to `     <a class="btn btn-cb2 btn-grey btn-success" href="{{url}}" target="_blank">{{_ "launch"}}</a>`
- [ ] Open up i18n/i18n.json and under `//buttons`, create a new `  "launch" : "Launch Hangout",` keyword. Don't forget the comma after this, and the comma on the line before it.

**Comment by eddieduro** [comment]
On it!

**Comment by lpatmo** [comment]
@eddieduro Great, thanks! Added the `claimed` label.

**Comment by sagarchoudhary96** [comment]
@eddieduro can i do that?

**Comment by adachiu** [comment]
@sagarchoudhary96 when the issue has a "claimed" label, it means it's already taken.

Please search for other issues that's labeled "not-claimed" :) Thanks!

**Comment by Subway19** [comment]
I would like to claim this.

**Comment by lpatmo** [comment]
@eddieduro Do you need any help with this issue? The if/else statements in hangout-item.html can be a little hairy, sorry...

**Comment by gytdau** [comment]
Issue solved, thanks @cosmologist10.

p.s. Wasn't Eddie supposed to do this one?

**Comment by lpatmo** [comment]
@gytdau True, but there was no update for a few days. We've since added (or at least there's a PR open!) to add something to contributing.md that says an issue can be un-claimed if there's been no update from the person who claimed it for 2 days. (The original claimant doesn't necessarily need to have solved the issue in two days, just update that they're working on it still or something.)

Anyway, thanks for closing this, @gytdau :)
