### ISSUE TITLE
Fix hangout cards on frontpage

### ISSUE THREAD

**Issue by Briix** [codebuddiesdotorg/cb-v2-scratch#259]
The hangout cards on the frontpage doesn't work very well on smaller screens and are in some cases unreadable.
<img width="321" alt="screen shot 2016-10-01 at 20 08 50" src="https://cloud.githubusercontent.com/assets/953798/19016160/f8c5cada-8812-11e6-9a90-07e28596bd0e.png">
<img width="320" alt="screen shot 2016-10-01 at 20 09 07" src="https://cloud.githubusercontent.com/assets/953798/19016159/f8c529ea-8812-11e6-88da-ec6061fe1da3.png">

I would like to solve this, if that's okay.

EDIT: Also unsure of how to actually add any labels.

**Comment by lpatmo** [comment]
@Briix You should be able to add labels now (added as collaborator).

And thanks for filing the issue! I'll add the label `claimed`.
