### ISSUE TITLE
"Go get a coffee or something. This is going to take a while" text is sad.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#260]
> That message "Go grab a coffee, this is going to take a while" makes me go all Homer_Simpson_Groan
> We need to make that less disappointing from a UX POV :)

Fix in this file:
`client/templates/admin/inc/loading.html`

Line 2:  
```
<p class="alert alert-info"><i class="fa fa-spinner fa-spin"></i> Go get a coffee or something. This is going to take a while.</p>
```

Maybe change the text to:
```Please wait a few seconds!```

Other text suggestions welcome!

**Comment by lungyiin** [comment]
How about "This will only take a moment"?

**Comment by lpatmo** [comment]
@lungyiin Sure!
