### ISSUE TITLE
Change text on button "Edit Hangout" to "Save Changes" in Edit Hangout Modal

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#275]
> The "Edit your Hangout" button can be called "Save changes" instead. Because it's more clear that the changes are being saved. Besides, the modal window already has the "Edit your hangout" title at the very top. From a UX perspective, it would be more clear to the user if the blue button was called "Save changes"
- @adachiu 

![image](https://cloud.githubusercontent.com/assets/4512699/19066617/f6394734-89ce-11e6-85dd-7b7713e7e929.png)

Relevant file to edit: `i18n/en.i18n.json` file.

**Comment by ollikarppinen** [comment]
I can do this one :)

**Comment by lpatmo** [comment]
@ollikarppinen Awesome!

**Comment by jllamasi** [comment]
@lpatmo I took the liberty of doing this issue. There's a PR open, thanks!

**Comment by lpatmo** [comment]
Thanks for the PR, @jllamasi! But working on it when @ollikarppinen had already left a comment to claim it was disrespectful to @ollikarppinen. This isn't a race! Please watch out for the `claimed` label in the future, or coordinate with the person who claimed the issue. Thanks.
