### ISSUE TITLE
Refactor css colour variables

### ISSUE THREAD

**Issue by Briix** [codebuddiesdotorg/cb-v2-scratch#282]
Since we're using sass we should really make use of it's variables.
I would like to clean up the sass and at least make sure that every colour has a variable name and that the variable name is used to style elements, i.e right now we have a `$bg-white` variable that is sometimes used and sometimes not and multiple definitions of `#fff`, `#ffffff` and `white` in the codebase.

So put colours into variables and replace current colours that aren't using variables right now.

**Comment by iamsk9** [comment]
Hello @briix I would like to solve this issue. I will change all the colors definitions with their respective variable names.

**Comment by adachiu** [comment]
@iamsk9 Looks like @Briix already put the `claimed` label on this issue. Please look for issues with the `not-claimed` label! Thanks!

**Comment by iamsk9** [comment]
ok thank you @adachiu

**Comment by lpatmo** [comment]
We could definitely do more SCSS refactoring in general, but let's make that a new issue since a PR has already been submitted for $bg-white, etc.
