### ISSUE TITLE
Edited - Changing this to countdown slack alert times.  (Old title - Time displayed on Slack for hangout alerts is in UTC as opposed to the user's respective timezone)

### ISSUE THREAD

**Issue by abhiii5459** [codebuddiesdotorg/cb-v2-scratch#286]
Discussed this with @lpatmo . 
I think this can be remedied by obtaining the timezone of each individual user using Slack APIs and adjusting dynamically.
This is a vague description. I'll add more to it.

Self-assigning to attempt to fix it.

**Comment by distalx** [comment]
@abhiii5459 
Heads up 
We are already storing _timezone_ details into `users` collection.

```
{
  ......
  "profile" : {
        "time_zone" : "Asia/Kolkata",
        "time_zone_label" : "India Standard Time",
        "time_zone_offset" : 19800,
        "firstname" : "",
        "lastname" : "",
        "avatar" : {
            "default" : "",
            "image_192" : "",
            "image_512" : ""
        }
    },
   ........
}
```

I am not sure if I understand the issue correctly, but it seems that  you are planning/thinking about  displaying hangout start time in _slack alerts_ according to individual user's preferance !! and if that's the case how are you planning to achieve that ? I'm just curious here.

**Comment by abhiii5459** [comment]
@distalx I understand that there's a dependency on the client side here and that's the challenge. I haven't really thought through it :( I'm led to believe that there's another issue that is tracking counting down the time left per hangout on slack notifications (to make the time left relative). If i can't figure out a satisfactory solution, I'll give up on this and look into contributing to the other issue

**Comment by distalx** [comment]
@abhiii5459 Yes, instead of displaying  `start date time` if we display `countdown time` that might work.

**Comment by abhiii5459** [comment]
@distalx I think we'll go ahead with that approach then . Starting work on that.

**Comment by abhiii5459** [comment]
Closing as solved.
