### ISSUE TITLE
Remove duplicate starbursts on single hangout post page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#288]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), highly inspired by the great job of the folks at [Hoodie](http://hood.ie). 👍
## 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
## 🎃🙀👕🔭😻 Hacktoberfest: Free T-Shirt from DigitalOcean for Your Open-Source Contributions!

If you haven’t yet, [sign up for Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt, which you can win after making four open pull requests.
## 🤔 What you will need to know to fix this issue

HTML, and some [Spacebars syntax](http://meteorcapture.com/spacebars/), since this app is coded using MeteorJS.

Hint: the file you'll need to look at primarily is `client/templates/hangout/hangout.html`.
## 🎯 The Goal

There is a starburst near the button, and on top of the button.

We need to remove the duplicate starburst at the top of the button. (See: screenshot below.)
![screen shot 2016-10-07 at 12 00 39 am](https://cloud.githubusercontent.com/assets/4512699/19181720/d706fb3e-8c23-11e6-9f16-d78107bc0511.jpg)
## 📋 Step by Step
1. 🙋 Claim this issue: Comment below. Please 🙏 only claim if you want to start working on it within a day. 
2. Please read our [contributing.md](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md) document to get started. You'll need to run the app locally, and create a branch for this issue.
3. Ask in this thread or in the #codebuddies-meta channel on our Slack if you run into any questions or problems.
4. Open a PR to master branch, mentioning this issue number. Simply opening a valid PR counts for your Hacktoberfest participation!
5. Someone will review your code, and once it's approved we'll merge it and deploy it to codebuddies.org.

**Comment by aj07** [comment]
I will go on it :100:

**Comment by wuworkshop** [comment]
@aj07 Sorry, but we'd like this issue to go to `first-timers-only` - as in someone who has never contributed to open source before. Perhaps you can work on some other [issues](https://github.com/codebuddiesdotorg/cb-v2-scratch/issues)?

**Comment by nachiketdhamankar** [comment]
Hey! I would like to work on this :)

**Comment by vedipen** [comment]
Can I work on this?

**Comment by lpatmo** [comment]
@nachiketdhamankar It's yours! Changing the `not-claimed` label to `claimed`.

@vedipen Sorry, @nachiketdhamankar commented first. If he doesn't want to work on it anymore we'll let you know.

**Comment by wuworkshop** [comment]
@vedipen This issue is for `first-timers-only`. Perhaps you can work on some other [issues](https://github.com/codebuddiesdotorg/cb-v2-scratch/issues) that haven't been claimed yet?

**Comment by nachiketdhamankar** [comment]
Hey guys! Is there any way I can contact you? Other than commenting here of course :)

**Comment by abhiii5459** [comment]
@nachiketdhamankar  Join the slack channel - codebuddiesmeet.slack.com  :)

**Comment by nachiketdhamankar** [comment]
@abhiii5459 I've not used slack before, but a quick search told me I've to get some invitation to join the channel :O

**Comment by abhiii5459** [comment]
Click on the link. Sign up for slack with your email id. When it prompts you to enter the channel, enter "codebuddiesmeet", provide your email id and password. You should be in the slack room :)

**Comment by nachiketdhamankar** [comment]
@abhiii5459 Thank you so much!

**Comment by wuworkshop** [comment]
@nachiketdhamankar Are you still working on this? If not, I can change the label back to `not-claimed`.

**Comment by abhiii5459** [comment]
@wuworkshop i believe he is working on it :)  he's been collaborating with me to set things up etc. @nachiketdhamankar, please correct me if I'm mistaken!

**Comment by nachiketdhamankar** [comment]
Hello! @wuworkshop @abhiii5459 Yes I've been working on it

**Comment by lpatmo** [comment]
@nachiketdhamankar Let us know if you need any help!

**Comment by lijulat** [comment]
Is this still claimed?

**Comment by abhiii5459** [comment]
@lijulat  You can take it!

@nachiketdhamankar I think the contributing.md guidelines have been stretched quite a bit on this one :) We can't let this be blocked for so long :( We'll find another issue for you :)

Marking it as not-claimed for @lijulat to respond and claim it.

**Comment by lijulat** [comment]
Yes I would like to claim this.

**Comment by abhiii5459** [comment]
@lijulat  it's yours. Adding the claimed tag.

**Comment by nachiketdhamankar** [comment]
Okay :)  @abhiii5459

**Comment by JohnHillegass** [comment]
@lpatmo I will claim it. This will be my first open source contribution :) and I should have it fixed by EOD Sunday.

**Comment by lpatmo** [comment]
Thank you @JohnHillegass! Let us know if you need any help with it.

**Comment by JohnHillegass** [comment]
@lpatmo thank you ! Actually, I do have a question. How can I view this locally ? I'd imagine its not as easy as running a simple server, correct ? *Reading the documentation now* but hoping you could give a quicker answer.

**Comment by JohnHillegass** [comment]
@lpatmo Actually ! I was wondering if I can update the meteor version to 1.4.2. Whenever I run meteor it tries to download and install the 1.3.4 release. Do I need this ? Or is it ok to upgrade the project ?

**Comment by lpatmo** [comment]
@JohnHillegass No need to update to 1.4.2, actually! There's a compatibility problem between 1.4 and deployment, which is why we haven't upgraded it yet. Let us know if you have more questions! (Can also ask in the #codebuddies-meta channel on Slack.)

**Comment by JohnHillegass** [comment]
@lpatmo please count me out. I can't get the app to run. There are errors having to do with MongoDb sometimes and most times when I have tried running it in a VM it times out after an hour of trying to install some packages.

**Comment by lpatmo** [comment]
@JohnHillegass Oh no, sorry to hear about the app running issues! No worries. Out of curiosity, were you on a Windows machine? We had another person complain that it wasn't working on their Windows machine, and there's an open issue about it -- but other Windows users have had no problem.

**Comment by lpatmo** [comment]
Closing this thread since it's getting a little long. Will reopen a new issue with the same issue. :)
