### ISSUE TITLE
Add documentation to contributing.md about how to seed a blank localhost:3000

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#289]
When new contributers first start up the app, there aren't any posts, and it's a hassle creating new fake hangouts.

@distalx solved this with a PR, but there's no documentation in contributing.md about how to run the app with the seeded posts/fixtures.

Task:
In contributing.md, add a line about how running the app (meteor with `"seeder":false,` in settings-development.json will seed a couple of hangout posts in localhost:3000.

**Comment by adnrs96** [comment]
Can i give this one a try?

**Comment by distalx** [comment]
@adnrs96 It's yours! I will change the claimed label. Thanks!

**Comment by sergeant-q** [comment]
Changes have been implemented. Closing issue
