### ISSUE TITLE
Limit "current status" update to 250 characters

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#29]
Doesn't have to be super short; just want to make sure people don't paste lorem ipsums in there to troll.

**Comment by adachiu** [comment]
250 characters per status seem like a lot to display in the status list. Lowering it to 140 like Twitter's character count could help keep statuses concise and to the point, while saving scroll space in the list of online statuses.

Not to mention that users would just be glancing at what others are working on. They probably won't read the whole 250 character statuses. Keeping it shorter makes more sense.

250 characters
> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.

140 characters
> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma

**Comment by sgtquezada** [comment]
I vote for the 140 characters.  Keeps it concise and to the point.

**Comment by lpatmo** [comment]
Cool, let's keep it at 140 characters. Anyone want to work on this bug?

**Comment by sheldonbarnes** [comment]
@lpatmo did anyone take this bug? I would love to learn, and contribute.
