### ISSUE TITLE
update getting started instruction in contributing.md.

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/cb-v2-scratch#290]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), highly inspired by the great job of the folks at [Hoodie](http://hood.ie). 👍

#### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)

### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt.

#### 🤔 What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process

####  🎯 The Goal

getting started instruction in `contributing.md` 
> How do I start up the app? meteor --settings settings-development.json

needs to be updated with following

>meteor npm install
>npm run meteor:dev

#### 📋 Step by Step
Working on your first Pull Request? You can learn how from this free series [How to Contribute to an Open Source Project on GitHub.](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

1. 🙋 Claim this issue: Comment below. 

2. Please read our contributing.md document to get started. 

3. Update the `contributing.md`

4. Open a PR to master branch, mentioning this issue.

Someone will review your code, and once it's approved we'll merge it

# 🤔❓ Questions
Ask in this thread or in the #codebuddies-meta channel on our Slack if you run into any questions or problems.

**Comment by pvskarthikeya** [comment]
Hey! I will do this.

**Comment by distalx** [comment]
@pvskarthikeya It's yours! I will change the claimed label. Thanks!

**Comment by aditya-konarde** [comment]
Hey @distalx ! I see that this issue has been claimed. Is there anything else I can do?

**Comment by distalx** [comment]
@aditya-konarde, There are still some other issues to work on, you can check out the remaining [issues](https://github.com/codebuddiesdotorg/cb-v2-scratch/issues?q=is%3Aissue+is%3Aopen+label%3Anot-claimed)!
