### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by Briix** [codebuddiesdotorg/cb-v2-scratch#293]
Would it make sense to have an .editorconfig file in place so we all follow the same standard, i.e. tabs gets converted to spaces, no trailing whitespaces etc.

If so I would like to implement it.
My suggestions would be:

```
charset = utf-8
indent style = spaces
trim trailing whitespaces = true
indent size = 4
```

**Comment by camilleriluke** [comment]
Very good suggestion @Briix!

After this [eslint](http://eslint.org/) would be great also :)

**Comment by wuworkshop** [comment]
Just recently came across this repo - https://github.com/sindresorhus/xo

**Comment by Briix** [comment]
@wuworkshop That looks really interesting! Maybe a good alternative to eslint?

**Comment by lpatmo** [comment]
This has been merged, but at some point we should update contributing.md to teach people how to take advantage of .editorconfig: http://editorconfig.org/. For example, I think if you're using Sublime, there's a plugin you should install: https://github.com/sindresorhus/editorconfig-sublime#readme

**Comment by Briix** [comment]
@lpatmo Created an issue for this now https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/405
