### ISSUE TITLE
CSS issue at a specific browser width

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#298]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), highly inspired by the great job of the folks at [Hoodie](http://hood.ie). 👍

#### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)

### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt.

#### 🤔 What you will need to know
CSS.

####  🎯 The Goal
`div.status-list` suddenly becomes much narrower at a specific browser width (see screenshot below):

![screen shot 2016-10-07 at 9 24 11 pm](https://cloud.githubusercontent.com/assets/4512699/19210321/9924c25e-8cd4-11e6-92d5-d6288dcc54a1.jpg)

## 📋 Step by Step

1. 🙋 Claim this issue: Comment below. Please 🙏 only claim if you want to start working on it within a day. 

2. Please read our [contributing.md](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md) document to get started. You'll need to run the app locally, and create a branch for this issue.

3. Ask in this thread or in the #codebuddies-meta channel on our Slack if you run into any questions or problems.

4. Open a PR to master branch, mentioning this issue number. Simply opening a valid PR counts for your Hacktoberfest participation!

5. Someone will review your code, and once it's approved we'll merge it and deploy it to codebuddies.org.

**Comment by mohit3011** [comment]
I'll work on this issue

**Comment by wuworkshop** [comment]
@mohit3011 Great. It's all yours. I've updated the label to `claimed`.

**Comment by mohit3011** [comment]
I have installed meteor 1.4.1.2 but when I try to run this command " meteor --settings settings-development.json" it gives error that meteor 1.3.2.4 is not installed and could not be downloaded

**Comment by wuworkshop** [comment]
@mohit3011 I just noticed we have an open issue #290 to update the contributing.md file in the getting started section. Could you try this instead to start the app?
```
meteor npm install
npm run meteor:dev
```

**Comment by mohit3011** [comment]
@wuworkshop 

>  `npm run meteor:dev`
is not working and displays the message " Sorry, this project uses Meteor 1.3.2.4, which is not installed and could not be downloaded"
.

**Comment by distalx** [comment]
Hi @mohit3011 , To install meteor `1.3.3.1`.
```
curl "https://install.meteor.com/?release=1.3.3.1" | sh`
```
A word of caution, though; it will replace your current meteor version with `1.3.3.1`.

**Comment by mohit3011** [comment]
Sorry but there is one more error

```
Errors prevented startup:                  
   
   While selecting package versions:
   error: Package version not in catalog: kadira:flow-router 2.12.1
   
   While refreshing package catalog to resolve previous errors:
   error: Network error: wss://packages.meteor.com/websocket: 139912972105536:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown
   protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
   
   
=> Your application has errors. Waiting for file change.

```
Actually I'm using a proxy network so I have changed the proxy settings in npm

**Comment by Kartikkh** [comment]
I want to work on this issue !

**Comment by wuworkshop** [comment]
hmm... @mohit3011 are you still working on this issue? or should @Kartikkh work on it?

**Comment by lpatmo** [comment]
@Kartikkh Feel free to take a stab at this, Kartik -- I'm not sure that Mohit was able to get his setup issues resolved, sadly. (And I couldn't figure out how to solve the error pasted.)

**Comment by kostakos14** [comment]
Is it still open?

**Comment by lpatmo** [comment]
@kostakos14 Yep!

**Comment by jmabry111** [comment]
Hey guys... I believe it was my character count PR that introduced this bug. (trying to move the counter over near the update button) If it's still open I'll be glad to push up a fix? Since the previous PR was my first contribution, I suppose I could indirectly be a `first-timer` 😛

**Comment by lpatmo** [comment]
@jmabry111 Go for it! (It's been a few days since @kostakos14 responded so I'm going to assume this issue is up for grabs again.)

@jmabry111 And feel free to ask in the #codebuddies-meta channel if you have any questions...

**Comment by jmabry111** [comment]
Thanks... PR #369 submitted 😄
