### ISSUE TITLE
View user number has different font

### ISSUE THREAD

**Issue by ericathedev** [codebuddiesdotorg/cb-v2-scratch#309]
<img width="934" alt="screen shot 2016-10-09 at 21 09 17" src="https://cloud.githubusercontent.com/assets/18517177/19222995/2ed2da48-8e65-11e6-86f0-97128e04beed.png">

The number 2 near the eye has a different font from the rest of the text.

**Comment by ericathedev** [comment]
I will be working on this 😄

**Comment by lpatmo** [comment]
@ericathedev Wow, good eye!

**Comment by abhiii5459** [comment]
Looks so "Times New Roman"-y :D

**Comment by yasirunilan** [comment]
is this assigned?

**Comment by lpatmo** [comment]
@yasirunilan Yes, I think @ericathedev has claimed this.

**Comment by gytdau** [comment]
Bug fixed.
