### ISSUE TITLE
Add instructions to contributing.md about how to add the CB repo as the upstream branch

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#311]
H/t to @wuworkshop for these links:

https://help.github.com/articles/configuring-a-remote-for-a-fork/

Then sync your fork by following these instructions:

https://help.github.com/articles/syncing-a-fork/

We need to add a step between instructions 5 and 6 on https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md that instructs new contributors who forked the repo how to set up the CodeBuddies repo as an upstream branch, so that when they `git pull` they'll get the latest changes on the CodeBuddies' `master` branch.

**Comment by madan96** [comment]
I would like to work on this issue.

**Comment by wuworkshop** [comment]
@madan96 go for it! I've updated the label to `claimed`.
