### ISSUE TITLE
[Deployment question] 'Cannot find module' error on cbv2-staging.herokuapp.com (our test staging site)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#324]
The error below didn't show up in `localhost:3000`, but showed up in http://cbv2-staging.herokuapp.com. If this were on localhost, I normally would do a `meteor npm install` to fix the problem. But not sure how to fix this on a live heroku instance.

![screen shot 2016-10-11 at 1 11 14 am](http://i.imgur.com/tDbLEuN.jpg)

**Comment by distalx** [comment]
@lpatmo @camilleriluke 
I'm not able to pinpoint the exact issue, either it's quill package itself or it's a [buildpack](https://github.com/AdmitHub/meteor-buildpack-horse), that we are using with heroku. Also other `npm` packages are working just fine so maybe it's `quill`.

The workaround is to add `quill.js` locally and I have tested it with heroku - [meteor-quill-example](https://meteor-quill-example.herokuapp.com/) which works just fine.

The changes for this workaround is on branch `issue-324`

**Comment by lpatmo** [comment]
Thanks @distalx! Do you want to submit branch `issue-324` as a pull request, with the `import Quill from './quill.js';` line change?

Btw, I'm not sure what does this was meant for:
```
  "test:full-app": "meteor test --full-app --driver-package=practicalmeteor:mocha --settings=settings-development.json --port 3100"
```

**Comment by camilleriluke** [comment]
> Btw, I'm not sure what does this was meant for:

@lpatmo that will run the unit tests

**Comment by lpatmo** [comment]
@camilleriluke Doh, of course! It was too late for me last night. -_-
