### ISSUE TITLE
Add Backers and Sponsors Sections To README

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#328]
Now that CB is on Open Collective (yay! 🎉 ), might be good to add a Backers and Sponsors section linking to the Open Collective page. Here are some other Open Collective projects that have what I'm referring to:

https://github.com/24pullrequests/24pullrequests
https://github.com/yoshuawuyts/choo

**Comment by sharynneazhar** [comment]
Can I work on this? :)

**Comment by lpatmo** [comment]
@sharynneazhar Go ahead! :) 

(On my plate, talking out loud: I have to figure out if there's more we need to do to finalize the page, and after that I think we can create a new issue to update the site to link to it, and then we can start contacting potential sponsors.)

**Comment by sharynneazhar** [comment]
Anything specific you guys would like to add to the verbiage?
