### ISSUE TITLE
Leave kudos on learnings/accomplishments

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#33]
Secondary feature, but: wouldn't it be cool to be able to leave kudos on learnings/accomplishments? That extra boost of encouragement!

**Comment by Luxisapex** [comment]
Working on this. Basically got it functioning, just wrapping up some styling and making sure it's bug free.

**Comment by lpatmo** [comment]
@Luxisapex Awesome! Let me know when you want to merge it into staging!
