### ISSUE TITLE
Slack alerts not appearing for scheduled hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#339]
@distalx found the bug -- something in `server/slack/methods.js`.

**Comment by distalx** [comment]
Right now alert for newly created hangout is not being posted to slack channels, maybe because of following code block.
```
if(minutes > 0)
{
    hangoutAlert(data)
}
```

@lpatmo I believe @abhiii5459  is already working on this feature, #326 . @abhiii5459 would you mind take a look at it ?

**Comment by abhiii5459** [comment]
@distalx @lpatmo I'll check it out today!

**Comment by lpatmo** [comment]
In the `issue-193-make-hangout-start/end-time-optional` branch, I was just able to get new Slack alerts appearing in #cb2-test *as long as* I changed the start time. May be a clue.

**Comment by abhiii5459** [comment]
@lpatmo  Then I think I have that covered in #338  :) PR has been raised! Can you please check?

**Comment by lpatmo** [comment]
Looks good! The only remaining bug I see happens when I create a hangout now and don’t change the start time. If I increase the start time by even a minute, the Slack notification is successful.

**Comment by abhiii5459** [comment]
Let me see if even that last nail in the coffin can be addressed

**Comment by sergeant-q** [comment]
I am not sure if this bug exists in the `master` branch because I am unable to reproduce this issue. (I am working in the master branch). Can someone confirm what branch should we be testing the Slack alerts not firing off for new hangouts?

**Comment by lpatmo** [comment]
@sergeant-q I see this in the `master` branch. If you schedule a hangout in advance, the alerts should appear... but not if you don't change the start time when you first click to create the hangout.

**Comment by sergeant-q** [comment]
@abhiii5459 I have a fix for this. Please take a look at it and let me know if you're good to go with it.

**Comment by abhiii5459** [comment]
@sergeant-q Checking.
