### ISSUE TITLE
Fix broken logo image in "cancelled hangout" email template

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#340]
![screen shot 2016-10-16 at 1 40 55 am](https://cloud.githubusercontent.com/assets/4512699/19416278/b0f32466-9341-11e6-9c11-88299ff8b957.jpg)

The fix probably needs to be in this template: `private/email-hangout-alerts.html`

**Comment by techtolentino** [comment]
I can give this a shot - reading contribution docs now...

**Comment by techtolentino** [comment]
Update - I have the fix, working on the PR

**Comment by lpatmo** [comment]
@techtolentino Great, thanks! Will add the `claimed` label here.
