### ISSUE TITLE
HTML: Update all the "Help us keep this project alive!" or "Sponsor us" links to point to the Open Collective

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#346]
I see a few places where we need to link to https://opencollective.com/codebuddies:

- [ ] FAQ page - very bottom
Change ```This project is hosted on DigitalOcean. You can help keep this project alive by becoming a sponsor of the month.``` to:
```This project operates in full transparency as a member of the <a href="http://opencollective.com/codebuddies" target="_blank">Open Collective</a>. Please help support our monthly server costs by becoming a <a href="http://opencollective.com/codebuddies" target="_blank">sponsor or backer</a>. You can keep this project alive!```

- [ ] The "Help us keep this project alive!" link on the footer needs to point to the Open Collective instead of to codebuddies.org/sponsor

- [ ] Add a bullet with a link to [CodeBuddies' Open Collective] under "Helpful Links" on http://localhost:3000/faq

- [ ] On http://localhost:3000/about, add a heading below "We are open-sourced" that says "We are fully transparent." The sentence should say: "Help us keep this project alive by becoming a <a href="http://opencollective.com/codebuddies" target="_blank">sponsor or backer</a>."

**Comment by stevenkayter** [comment]
On it

**Comment by richa-coder** [comment]
hey ! Is the bug fixed? Can i work on it?

**Comment by lpatmo** [comment]
@richa-coder Looks like @stevenkayter tackled the first three bullet points and opened a pull request for faq.html. You're welcome to tackle the remaining three!

**Comment by stevenkayter** [comment]
I've tackled the rest of the bullets. Please check

**Comment by richa-coder** [comment]
Stephen,did u tackle all the bullets? Nothing left for me to do :(



[image: --]

Richa Singh
[image: https://]about.me/richa-singh
<https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
