### ISSUE TITLE
Give host the ability to trash hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#35]
Bonus: everyone who signed up for a hangout should get a notification that it was cancelled.

**Comment by sgtquezada** [comment]
Working on this feature!

**Comment by sgtquezada** [comment]
Code complete. Ready for review.

**Comment by lpatmo** [comment]
Reviewing the branch now!

**Comment by lpatmo** [comment]
Looked over your code... looks good!

A UI thing: what do you think about replacing:

<button id="delete-hangout" class="btn btn-xs btn-danger">delete hangout</button>

with something like:

<span id="delete-hangout"><i class="fa fa-trash-o"></i></span>

I'm thinking that using the fontawesome icon would look better than the red button.

**Comment by sgtquezada** [comment]
Ok! I will look into a good font-awesome icon that works for delete. I have updated the "on cancel" prompt to close the modal as opposed to a separate modal confirming after.

**Comment by sgtquezada** [comment]
Updates made! Please review

**Comment by lpatmo** [comment]
Have merged the branch `fix/issue-35-trash-hangouts` into `staging`, and deployed it to http://cbv2-staging2.meteor.com/#.

Small changes I made before merging:
- Changed #delete-hangout to .delete-hangout, since it's possible that a user could have multiple hangouts they want to delete on the page. 
- Turned the red button into a trash icon only, so that it takes up less space on the page. (I don't think we should make the ability to delete super red and loud.)

Thanks, @sgtquezada -- great work!
