### ISSUE TITLE
Breathing room around icons

### ISSUE THREAD

**Issue by techtolentino** [codebuddiesdotorg/cb-v2-scratch#351]
It would be nice to have a bit more spacing (padding/margin) around the icons in the contributors popovers. I believe that this would enhance usability and make for a better UX.

![screen shot 2016-10-18 at 7 38 18 am](https://cloud.githubusercontent.com/assets/6276074/19478007/68d290b0-9506-11e6-98ae-45329261d258.png)

**Comment by salaxander** [comment]
I can take care of this if it's up for grabs!

**Comment by techtolentino** [comment]
@salaxander I'd wait for @lpatmo to comment on if it's something they'd want. But thanks for volunteering to handle it!

🎉

**Comment by adachiu** [comment]
@salaxander @techtolentino Thanks for pointing that out. It does need some padding/margin around the icons. Please go ahead and take this issue.

I'm sure @lpatmo agrees too :)

**Comment by lpatmo** [comment]
Yep, no complaints here -- thanks @salaxander and @techtolentino!

**Comment by salaxander** [comment]
@lpatmo @adachiu PR merged :)

**Comment by techtolentino** [comment]
@lpatmo can this be closed?

**Comment by lpatmo** [comment]
Yep! Closing now. :)
