### ISSUE TITLE
Footer placement

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#353]
The footer is currently stuck at the bottom of the viewport. The footer should show when you scroll to the bottom of the page instead. That way, the footer won't cover the content within the viewport.

This applies to all pages.

![screen shot 2016-10-18 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/13413986/19496332/e2c7511e-953b-11e6-8c1b-580e2ca25f0e.png)

**Comment by sharynneazhar** [comment]
I can work on this :) 

Just to clarify, we don't want the footer to be sticky, correct? Only visible when the user scrolls to the end of the page?

**Comment by adachiu** [comment]
@sharynneazhar correct. Thanks!
