### ISSUE TITLE
Add 'Fixes' to Pull Request template

### ISSUE THREAD

**Issue by techtolentino** [codebuddiesdotorg/cb-v2-scratch#357]
Currently, if a Pull Request is merged amd the author didn't reference an issue with either a "Fixes" or "Closes", the issues doesn't get closed automatically.

To automate the process, the pull request template can be updated to include something like:

`Fixes #< issue number >`

**Comment by distalx** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this?

**Comment by techtolentino** [comment]
I can... But someone else also can - could be an easy #hacktoberfest PR!

(if no one claims it by 4am CST, I'll do it)

**Comment by sharynneazhar** [comment]
This sounds like a great idea. I would love to learn and give this a try!

**Comment by techtolentino** [comment]
@sharynneazhar have you had a chance to look at this?

**Comment by sharynneazhar** [comment]
Oh, I don't realized I was assigned since I didn't get a response haha. Sorry! I will work on it in the next day or two 🙂

**Comment by sharynneazhar** [comment]
PR ready for review :)
