### ISSUE TITLE
Remove dodgerblue background color from "Upcoming" text on single post page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#372]
Should look like this:

![screen shot 2016-10-26 at 11 17 16 pm](https://cloud.githubusercontent.com/assets/4512699/19756586/8391ff12-9bd2-11e6-99e7-9b4e9f0a317d.jpg)

How to recreate the bug:
1. In localhost:3000, after you're logged in, create a hangout that starts sometime in the future (e.g. tomorrow or in an hour)
2. Click on the title to see the single post page.
3. You'll notice a blue bar across the "Upcoming" text. 
4. Change the background color to $bg-white in the appropriate .scss file.

**Comment by kindlingscript** [comment]
Hi @lpatmo, I'm up for claiming this. I've noticed the font color ("Starting in # hours") clashes with the $bg-white (already started working on it), so is $primary-grey the appropriate color to change the font to?

**Comment by lpatmo** [comment]
Hi @kindlingscript! Yep, $primary-grey is appropriate. :) Thanks! And let me know (or ask in #codebuddies-meta) if you have other questions.
