### ISSUE TITLE
Extra padding on landing page & mobile padding/width

### ISSUE THREAD

**Issue by kindlingscript** [codebuddiesdotorg/cb-v2-scratch#374]
1) When accessing the site on a Macbook Pro in Chrome, Firefox, and Safari, there's two sections on the landing page that have extra padding (top and bottom, respectively) that may not be needed. Here's the two sections, as screenshot recently on codebuddies.org:

<img width="1436" alt="screen shot 2016-10-27 at 2 20 32 am" src="https://cloud.githubusercontent.com/assets/13127241/19758234/cd1f5836-9bec-11e6-964d-41085e2b97f5.png">

----------

<img width="1434" alt="screen shot 2016-10-27 at 2 22 00 am" src="https://cloud.githubusercontent.com/assets/13127241/19758236/cfc75dd6-9bec-11e6-88f9-55e10745b0de.png">

To point it out specifically, I'm talking about the extra blue background on top of "Learn and chat about code!" in the first screenshot, and the extra blue background underneath "codebuddiesmeet.slack.com team" in the second one. Using Chrome DevTools to take out the padding, the two then look like this:

<img width="1437" alt="screen shot 2016-10-27 at 2 30 25 am" src="https://cloud.githubusercontent.com/assets/13127241/19758396/79ba7ff8-9bed-11e6-806b-6f23d02aeda6.png">

----------

<img width="1438" alt="screen shot 2016-10-27 at 2 30 05 am" src="https://cloud.githubusercontent.com/assets/13127241/19758398/7d039ef6-9bed-11e6-9257-ac226fbac1c2.png">

With two changes to padding in each respective area, the content at the top of the landing page isn't pushed down anymore, and the background above and below the second screenshot's content is evened out, cleaning up the design some. Also checked on my iPhone Chrome app, same issue in it. 

2) While checking the site out on my phone, I noticed the following:

<img width="323" alt="screen shot 2016-10-27 at 3 01 00 am" src="https://cloud.githubusercontent.com/assets/13127241/19759271/cdb7ac08-9bf1-11e6-8fc1-44cb5de1c393.png">

There's no left/right padding for the paragraph that starts with "On the CodeBuddies site," and the "Join Hangouts" example image is too small to view and read properly. I also went into DevTools and believe I found where these can be fixed.

I'd like to work on these two things if it looks all right to do so. Let me know! 🙂

**Comment by adachiu** [comment]
@kindlingscript please go ahead and fix the padding! 

For the padding above the "Learn...", you can try to trim that by half b/c the screenshot of the change you made is slightly too crammed at the top. Thanks!
