### ISSUE TITLE
Navbar link color

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#380]
Currently the nav bar link color is `$cta-blue`, let's change it to match the link colors of the footer.
![screen shot 2016-10-28 at 5 43 34 pm](https://cloud.githubusercontent.com/assets/13413986/19826092/ed67ee54-9d37-11e6-893e-ea4d4e843d04.png)

In `_navbar.scss`
- [ ] Change the color variable to `$secondary-grey`

- [ ] Update the `a:hover` color to `$cta-blue`

**Comment by morris-jason** [comment]
I'll do this and submit a PR. Thx.

**Comment by adachiu** [comment]
@morris-jason perfect, thanks!

**Comment by morris-jason** [comment]
There's no a:hover in _navbar.scss.

**Comment by adachiu** [comment]
Maybe try to find if there is a global a:hover in base.scss and change or add it there.

If there is a a:hover in base.scss , then we should also update the footer.scss to remove the redundant a:hover

**Comment by morris-jason** [comment]
That's it - thanks!

**Comment by morris-jason** [comment]
Please review https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/381
