### ISSUE TITLE
Add a $ icon to the footer that links to opencollective.com/codebuddies

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#387]
Add a fontawesome $ icon to the right of the Facebook icon on the footer:
![screen shot 2016-10-29 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/4512699/19832151/172bf7d2-9dd1-11e6-9d08-3990302e9da1.jpg)

Here's the fontawesome icon: http://fontawesome.io/icon/usd/

The new icon should link to http://opencollective.com/codebuddies, and open up in a new tab.

**Comment by adachiu** [comment]
@lpatmo I'm not sure if the $ icon is the best choice under "Connect with Us" since it might be misconstrued as paying for CB.

The bottom line of text already mentions sponsoring. However, we could put more emphasis to the line. Or better yet, add a section on About and Home page that emphasizes sponsorship.

**Comment by lpatmo** [comment]
@adachiu Ah, good point. I mainly thought it'd be a good idea to include a pointer to the Open Collective as one of the handy, easily-grabbagle links. Maybe we can find a better icon for it.

**Comment by adachiu** [comment]
@lpatmo I wonder if there is an open source icon in Font awesome. However, is the open source icon well-known? If people don't recognize the icon, they might not click it.

We could emphasize the bottom sponsor text instead.

**Comment by lpatmo** [comment]
Maybe http://fontawesome.io/icon/circle-o-notch/? The Open Collective icon sort of looks like this open circle.

**Comment by lpatmo** [comment]
@adachiu Or to emphasize the Open Collective link a bit better, maybe we can move it up like this?

![screen shot 2016-10-29 at 12 53 48 pm](https://cloud.githubusercontent.com/assets/4512699/19832363/c6a2d500-9dd6-11e6-9d8e-31485a45dbb9.jpg)

**Comment by adachiu** [comment]
@lpatmo that feels a bit off. Hmm how about adding one more column? So beside "Connect with Us" will be another column called "Help Sponsor Us" and then the text under it.

**Comment by lpatmo** [comment]
Screenshot upcoming! 

![screen shot 2016-10-29 at 12 53 48 pm](https://cloud.githubusercontent.com/assets/4512699/19832402/c4cdc1c6-9dd7-11e6-9628-2ba18b0da366.jpg)

How does it look?

**Comment by lpatmo** [comment]
(Accidentally uplodaed the old screenshot; edited with the new one.)

**Comment by adachiu** [comment]
Looks good! It adds emphasis to the sponsorship now. Can we decrease the gutter between the 3 text columns? It looks a bit too far apart.

**Comment by adachiu** [comment]
We could probably get rid of that divider line at the very bottom as well if we are not putting any additional info there. Did you want to put license info? Or add back the "Built by people all around the world ❤️" text? Might be a nice friendly touch.

**Comment by adachiu** [comment]
Could we not have "-5", because it's awkwardly long 🙈. Let's have the text fill two lines!

**Comment by lpatmo** [comment]
Having it be 3-2-2-2 introduces a lot of blank space on the right, though. :/

**Comment by adachiu** [comment]
Can't move the 3 text columns to float right?

**Comment by lpatmo** [comment]
Ohhh, yeah, we can do 6-2-2-2! So there'll be a space to the right of the logo, but that's okay.

**Comment by lpatmo** [comment]
Thanks Ada! I'm going to close this thread and open a new one since this is getting long.

Sorry for the changing specs, @stratosgear and @bennycarlsson -- will tag you in the new issue thread in case you're interested.
