### ISSUE TITLE
Change CSS color on hover for links in the footer

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#388]
On the header, the links turn #333 when they're hovered over.

On the footer, the links don't change color on hover.

For consistency, we should make the links in the footer change color on hover too.

We need something like this added to _footer.scss:

```
#footer a:hover {
color: #333;
}
```

**Comment by adachiu** [comment]
I thought this was fixed in #381 
Global a:hover color $cta-blue

**Comment by lpatmo** [comment]
Strangely it looks fixed on codebuddies.org, but it doesn't look fixed on my localhost:3000.

**Comment by adachiu** [comment]
@lpatmo Wouldn't it be better if the `a:hover` had a global color variable? instead of putting the color in footer and navbar separately?

**Comment by lpatmo** [comment]
@adachiu Yes! I was lazy here because I wasn't sure how we'd distinguish between the header/footer links vs. the links in the hangout cards, for example. Maybe this theoretically should really be in a new _typography.scss file with #header a, #footer a { color: $black; } or something.

**Comment by PedroCSSilva** [comment]
Is this fixed?

**Comment by bu7ch** [comment]
claimed or not ?

**Comment by lpatmo** [comment]
@PedroCSSilva @bu7ch Not claimed, if you'd like to work on moving it out of _footer.scss (and creating a _typography.scss). And finally, double-checking that the link hovers for the rest of the content page isn't affected.

**Comment by PedroCSSilva** [comment]
Ok, I'll try to do it!

**Comment by Briix** [comment]
Might be worth considering creating a small utility class for this.
Something like `.hover--grey { color: #333 }` and then just add that class to where we want the links to be grey on hover. That way we won't have to worry about accidentally messing with other elements' styling
