### ISSUE TITLE
Hangout FAQ text is too long, says Ada

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#39]
You can create three types of hangouts:

 silent hangout
 teaching hangout
 collaboration hangout
FIRST THING to do when you join a hangout is to turn off the video camera and the microphone by clicking on the   icons!

A  silent hangout is like a virtual coffeeshop for people who want to be productive. You can make the hangout topic general enough so that people can work on different things, or the topic could be about working through the same tutorial or coding exercises. As a silent hangout host, you can decide to do a quick microphone-on check-in near the end of the session, but in general participants will expect the majority of the hangout to be microphone-off.

A  teaching hangout functions as a space where you can teach a concept or walk participants through a codebase. This is your way of sharing your knowledge and your skills!

If you create a  collaboration hangout, you can use the hangout as a space to "pair program" on a coding exercise, talk through a chapter of a coding tutorial together, or work on an open-sourced project with anyone who might be interested.

General tips

You can use the CodeBuddies Slack OR the Google Hangout chat box to chat and type questions.
Screensharing is always optional, but some of us like to do it so that we don't get distracted by Facebook or YouTube during a  silent hangout, or so that we can more easily track where everyone is at and debug issues more easily during a teaching or  collaboration hangout.
Google Hangouts lets multiple people screenshare with each other at the same time. You can click on a person's individual icon to see their screen.

**Comment by wuworkshop** [comment]
@lpatmo Maybe this issue should be part of either #10 or #22? 3 issues about the FAQ page seems a bit much. ^^'
