### ISSUE TITLE
(HTML/CSS) redesign of footer to follow this screenshot

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#393]
Let's change the footer from this:
![screen shot 2016-10-29 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/4512699/19832630/ae4aca92-9ddd-11e6-9a13-a90359c9dff5.jpg)

... to THIS:
![screen shot 2016-10-29 at 1 09 12 pm](https://cloud.githubusercontent.com/assets/4512699/19832628/9ac550aa-9ddd-11e6-99c2-1232b7fb238b.jpg)

Two changes to the screenshot above:
- remove the ___ border at the bottom
- The grid layout should be 6-2-2-2, not 3-2-2-5 as shown above.
- Add a "Built By Cool People Around The World!" below the "Help sponsor us!" text

If you'd like to take this bug, PLEASE leave a comment in the thread to claim it.

And be sure to read our [contributing.md](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md) docs!

(cc @stratosgear and @bennycarlsson in case you're interested)

**Comment by garri-ribeiro** [comment]
hey i will try to fix this :)

**Comment by lpatmo** [comment]
@maryna-yanul @garri-ribeiro had already commented here to claim this issue, sorry!
