### ISSUE TITLE
Odd hover behavior on contributors section of About page

### ISSUE THREAD

**Issue by newswim** [codebuddiesdotorg/cb-v2-scratch#404]
![hover](https://cloud.githubusercontent.com/assets/6667096/19843935/249de306-9ef5-11e6-9076-3c39d1ef42a9.gif)

I think the mouseover event trigger should have 20-30px buffer around the pop-up, so you don't have to follow the pseudo element to access links, and the behavior is a little more predictable.

Possible fix could be using an "invisible box" as a parent div and tying the event actions to that.

Tested on Chrome 54.

**Comment by lpatmo** [comment]
Thanks for filing this, @newswim.

**Comment by anmrdz** [comment]
Working on it.

**Comment by kevincoleman** [comment]
I’ll take a look into this. Other options might be adding a slight delay after mouse-out before the window disappears, or widening the hit box of the “bridge” that lets your mouse get there.

**Comment by kevincoleman** [comment]
PS, @newswim, nicely described with the video. Made it easy to spot. 👍

**Comment by newswim** [comment]
No problem, that's awesome!

btw, I used this app for making the gif, very easy to use: http://www.cockos.com/licecap

**Comment by kevincoleman** [comment]
Ooooh, slick! I’ve been using droplr, but when you hit the monthly upload limit it gets slightly cumbersome. Good share. 😄
