### ISSUE TITLE
Add editorconfig section to contributing.md

### ISSUE THREAD

**Issue by Briix** [codebuddiesdotorg/cb-v2-scratch#405]
As @lpatmo said (#293), since we're now including an .editorconfig in the project (#337) it would be good to include how to take advantage of the this in contributing.md, so new and current contributors knows how to install and use it in their current editor.

http://editorconfig.org/#download already has a good list of plugins for various editors. I don't know if it's a complete list, but it might be a good starting point.

**Comment by Briix** [comment]
@lpatmo Was this done?

**Comment by lpatmo** [comment]
Whoops, closed this by mistake, sorry!

**Comment by techtolentino** [comment]
I can take this 😄
