### ISSUE TITLE
prevent “join" if the hangout has already completed

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#41]
Disable the button if the hangout says "mastered X minutes ago..."

Should be a straightforward fix if anyone wants to take it on.

**Comment by Luxisapex** [comment]
Added this unless-statement in hangout-item.html  :

{{# unless getIsDone this}}
  <button id="join-hangout" class="btn btn-cb2">{{_ "join"}}</button>
{{/unless}}

which should hopefully skip displaying the button in mentioned case, but I can't really test it locally since I am the only user.

**Comment by lpatmo** [comment]
Merged into http://cbv2-staging2.meteor.com/. Thanks, @Luxisapex!
