### ISSUE TITLE
Delete hangout functionality not working on mobile (delete icon does not trigger modal)

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/cb-v2-scratch#42]
If you access the site on mobile, when attempting to click on the delete (trash) icon - nothing happens.  The confirmation modal does not get triggered.  

Tested on iOS with Safari and Chrome browser.

**Comment by distalx** [comment]
There is one more issue with this The confirm button on modal is also not working. So user is not able to delete the hangout at this stage.

**Comment by lpatmo** [comment]
This was fixed here: https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/56
