### ISSUE TITLE
Remove duplicate starbursts on single post page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#422]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), highly inspired by the great job of the folks at [Hoodie](http://hood.ie). 👍
## 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
## 🎃🙀👕🔭😻 Hacktoberfest: Free T-Shirt from DigitalOcean for Your Open-Source Contributions!

If you haven’t yet, [sign up for Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt, which you can win after making four open pull requests.
## 🤔 What you will need to know to fix this issue

HTML, and some [Spacebars syntax](http://meteorcapture.com/spacebars/), since this app is coded using MeteorJS.

Hint: the file you'll need to look at primarily is `client/templates/hangout/hangout.html`.
## 🎯 The Goal

There is a starburst near the button, and on top of the button.

We need to remove the duplicate starburst at the top of the button. (See: screenshot below.)
![screen shot 2016-10-07 at 12 00 39 am](https://cloud.githubusercontent.com/assets/4512699/19181720/d706fb3e-8c23-11e6-9f16-d78107bc0511.jpg)
## 📋 Step by Step
1. 🙋 Claim this issue: Comment below. Please 🙏 only claim if you want to start working on it within a day. 
2. Please read our [contributing.md](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md) document to get started. You'll need to run the app locally, and create a branch for this issue.
3. Ask in this thread or in the #codebuddies-meta channel on our Slack if you run into any questions or problems.
4. Open a PR to master branch, mentioning this issue number. Simply opening a valid PR counts for your Hacktoberfest participation!
5. Someone will review your code, and once it's approved we'll merge it and deploy it to codebuddies.org.

**Comment by nehalita** [comment]
hello! @lpatmo @mckpm and I are working on this
