### ISSUE TITLE
character count for status update

### ISSUE THREAD

**Issue by sheldonbarnes** [codebuddiesdotorg/cb-v2-scratch#44]
display a character count for the status update so users will know when they will hit the 140 limit

**Comment by sheldonbarnes** [comment]
![status_length](https://cloud.githubusercontent.com/assets/10457072/13544196/5cbfb00a-e241-11e5-95d2-a11aeb3aecd9.png)
Sample of what it would look like.  Any feedback?

**Comment by lpatmo** [comment]
Cool!! Maybe we should move "I'm interested" on top of the icons so it doesn't look too squeezed. (Just thinking out loud -- don't have to worry about for the purposes of this issue.)

**Comment by adachiu** [comment]
Nice work! I agree with @lpatmo about moving the "I'm interested in" on top to make it  look less crowded.

Or the "140" character count could be moved up into the text input box at the bottom right corner and make the "140" have a light grey. This way, we can have the "I'm interested in" aligned horizontally with the icons. @lpatmo  @sheldonbarnes What do you think?

**Comment by adachiu** [comment]
Maybe like this?

![screen shot 2016-03-05 at 12 24 43 am](https://cloud.githubusercontent.com/assets/13413986/13546653/e191152c-e268-11e5-885b-dd984290440b.png)

**Comment by sheldonbarnes** [comment]
Yes, I like that.

**Comment by sheldonbarnes** [comment]
@sgtquezada would it be okay to utilize the session for keeping track of the status text length:

Respond to the key presses:
` 
 'keyup #working-text': function(event) {

        var currentStatus1 = $('#working-text').val();
        Session.set('statusTextLength', (140 - (currentStatus1.length) ).toString());
  }
`
helper function for getting the current characters left:

`
statusTextLength: function() {

    if (Session.get('statusTextLength') == undefined)
      return 140;
    else
      return Session.get('statusTextLength');
}
`

Finally HTML:

{{ statusTextLength}}

**Comment by sgtquezada** [comment]
@sheldonbarnes not a bad idea. Are we 'checking' or validating the character count on the server side before we do the insert into the collection? I don't recall if we are or not.

**Comment by sheldonbarnes** [comment]
The session is only involved in displaying the count to the user.  I will check the server code for validation.

Is there any other way to store the character count session side?

**Comment by sebbel** [comment]
why not just count it when the user is done typing, or am I missing something?

**Comment by sheldonbarnes** [comment]
We should check server side too.  See screenshot above with visual feedback for characters remaining on client side

**Comment by lpatmo** [comment]
@sheldonbarnes When you have a chance, can you push your branch up? (Couldn't find the one related to issue this issue #44). Thanks!

Question: how important is it to check for the character count server-side? My impression was that client-side was enough, but I may be missing something...

@sebbel I think we want the count to change *as* the user's typing, like on Twitter.

**Comment by sheldonbarnes** [comment]
I spoke with Sgt yesterday afternoon about what I've developed.  I am still working on the logic, and styling.  I should have things in order soon for testing.

It is normally a good security practice to do server side validation as well.  In this case we are trying to limit character count.  I am open to either way.

If we have higher priority tasks to tackle, we can circle back on the server side validation.

**Comment by sergeant-q** [comment]
Has this been completed yet? Otherwise, we can add it to hacktoberfest for some help.

**Comment by lpatmo** [comment]
Issue update:

@JelaniThompson opened a pull request on this issue, but it contained an upgrade to meteor 1.4. From reading the discussion in #codebuddies-meta, @William-R-Wilson volunteered to try to cherry-pick the fix tomorrow, but actually... I think a safer solution is to open up a new pull request with the meteor update commit reverted, or committed over, so that we have the record of the merge in a pull request.

**Comment by distalx** [comment]
I believe this issue has been resolved in #235 and related ongoing issue could be found at #236 ,
