### ISSUE TITLE
Ability to edit a learning

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#46]
Give users the ability to edit their own learnings.

**Comment by sheldonbarnes** [comment]
![screen shot 2016-03-05 at 10 29 41 am](https://cloud.githubusercontent.com/assets/10457072/13548388/420875ae-e2bd-11e5-982e-efc44305947b.png)

What about a font awesome classed button for edit?  When the user clicks the edit button, it populates the existing learned text back into the text area.  When the user clicks the Update button, it updates it with all the behind the scenes magic.  By utilizing the existing text area, we avoid creating a separate area for editing.

**Comment by lpatmo** [comment]
Alternatively, on click of the edit button, we could hide the existing span or div that contains the learning and then show a textarea on top of it that contains the content of the learning. 

Same idea as before basically, except user would be editing/typing directly over the post instead of on top.

**Comment by lpatmo** [comment]
(Actually, never mind about my comments before... my excuse was that I was on an airplane. Totally makes sense to have the text re-populate back in the "today i learned" textarea, IMO.)

**Comment by William-R-Wilson** [comment]
I'm going to give this a shot tonight.

**Comment by William-R-Wilson** [comment]
Done, merged and pushed.  Please take a look before we close the issue.

**Comment by distalx** [comment]
It works just fine.
But I believe that we should also use `this.userId` with `editLearning` and `deleteLearning` methods.
And it would be a good idea if we show some _alert_ message on deletion.

**Comment by William-R-Wilson** [comment]
I believe you are right!  Silly me forgetting about that detail.  I'll do some more work tonight.

**Comment by William-R-Wilson** [comment]
So I have it set to where you can't see the edit/delete buttons if you aren't the owner of a learning.  I assume that was what you meant distalx?  

I also added an confirm on delete.  I pushed these changes to a new branch and have not merged yet:  fix/add-userId-to-edit-learning if anyone wants to check it out before merging.  \m/

**Comment by sergeant-q** [comment]
@William-R-Wilson the issue @distalx is referring was an oversight in the delete and edit hangouts server methods.  This has been addressed in the following committ https://github.com/codebuddiesdotorg/cb-v2-scratch/commit/f7b8665a96b9c32f17d84d16b13f59c7b30996f6

Take a look at what was done there to apply the same **security check** on the remove or update operation on the collection.  In a nutshell, we must ensure the user who is attempting to edit/delete the learning is the owner!

**Comment by William-R-Wilson** [comment]
Right on.  I modeled my own code on the hangouts methods.  I wondered if server side authorization was needed as well.  I can make sure this gets done in the next couple days and will post here when it's done.

**Comment by William-R-Wilson** [comment]
This seems to be working in the master branch.  I've tested it locally by logging in with two different accounts.

**Comment by lpatmo** [comment]
Agreed, @William-R-Wilson! Closing this issue. :)
