### ISSUE TITLE
Ability to edit a hangout post

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#47]
Give hosts the ability to click on an "edit" icon to edit their own posts.

**Comment by sheldonbarnes** [comment]
considering tackling this after the 140 count feature on the status update

**Comment by lpatmo** [comment]
Itching to take a stab at this issue now too. :)

**Comment by lpatmo** [comment]
@sheldonbarnes I pushed up the `feature/issue-47`branch: https://github.com/codebuddiesdotorg/cb-v2-scratch/commit/785bf783cc6dea5ab436f24f42b27003f571597c

Not quite working yet, though, because in api.js `Meteor.hangouts.update` can't quite figure out which post it's supposed to be updating.

**Comment by lpatmo** [comment]
This is resolved in three commits: 785bf783cc6dea5ab436f24f42b27003f571597c, d3b3b4d84ce10c69e007480cd8919c793c55020c, and cd67b4f7472ec1c4c15eb5ef9d1c12986defb9fe.

Would love feedback/testers on cbv2-staging2.meteor.com.

**Comment by lpatmo** [comment]
Note: re: that problem I had last night... to pass the data forward into another JS file, I ended up doing this:

hangout-edit.js:
```
  var hangoutId = Session.get('hangoutId');
      console.log(hangoutId + ' second');

Meteor.call('editHangout', data, hangoutId, function(err, result) { ... }
```

And then in api.js:
```
editHangout: function(data, hangoutId) {
check(...etc.)
Hangouts.update({_id: hangoutId}, 
      {$set: 
        {
         topic: data.topic,
         description: data.description,
         start: data.start,
         end: data.end,
         type: data.type
      }
    });
    return true;
  },
```

**Comment by nestevez7** [comment]
Edit successful on multiple tests. The text fields and radio buttons were easy to edit however, the date/time was tricky as I'm use to clicking on the actual input to edit and not the time icon.

**Comment by lpatmo** [comment]
Thanks for testing, @nestevez7! Agreed that date/time editing is tricky, but if the user saves in lowercase ("am") instead of uppercase ("AM") it results in an error. I'll file this issue in another bug. 

Closing this particular bug for now.
