### ISSUE TITLE
Reminder emails should go out 24 hours (and 2 hours?) before a hangout starts.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#49]
Those interested in working on this issue should look at what @sgtquezada committed to get email notifications working whenever someone cancels a hangout. (And also look at the pretty email template!)

This issue is pretty important because currently on hangouts.codebuddies.org, people often sign up for a hangout without showing up.

The email notification should include a note reminding participants that they can update their RSVP in this new app if they need to unjoin for whatever reason.

I'm not sure exactly if it should be 24 hours + 2 hours or something else; we can discuss here.

**Comment by sergeant-q** [comment]
This has been implemented with PR #107 - closing issue.
