### ISSUE TITLE
Add user fields to the user profile page -- so users can add bio info. and links about themselves

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#52]
There should be an additional "profile information" textarea that individual users can edit to insert links or add any bio description they want.

**Comment by sergeant-q** [comment]
Can we have someone mock this up? @adachiu (**you da man!**)

**Comment by adachiu** [comment]
Like issue 61?
https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/61

The text area could be bigger. We could also put an icon for users to edit their information.

**Comment by sergeant-q** [comment]
Yes, I guess issue #61 is a re-haul of the user profile.  I think what we need is a mock up on what the **edit view** would look like and what fields a user can edit/update. 

And yes - an _edit_ icon would be nice to add (and only visible to the user themselves).

**Comment by sharynneazhar** [comment]
Is this still open? I would like to try working on this :)

**Comment by sharynneazhar** [comment]
Or is this already done with issue #147?

**Comment by lpatmo** [comment]
@sharynneazhar This issue is still open! I'll mark this as claimed if you want to work on it. :)

**Comment by sharynneazhar** [comment]
@lpatmo Sweet, thank you!

**Comment by lpatmo** [comment]
Np! Let us know if you have any questions about it.

**Comment by sharynneazhar** [comment]
Like @sergeant-q suggested, do we have a mock-up I should follow for this?

**Comment by lpatmo** [comment]
@sharynneazhar 

![image](https://cloud.githubusercontent.com/assets/4512699/19044983/765a135a-894b-11e6-8e5e-31c79d6b5aa6.png)

This is the only mockup we have so far. Maybe on the right-hand side (in place of the quote), we could have an "Edit Profile" button, and when that gets clicked on a couple of fields open up, with:

Twitter   [    ]
Github  [    ]
Slack [    ]
Bio [    ]
Programming Interests [     ]
?

The links for twitter/github/Slack could show up underneath the profile picture on the left-hand as shown in the mockup, and the Bio description and the Programming Interests description could appear on the right-hand side beneath the Edit button.

Thoughts welcome!

**Comment by distalx** [comment]
Resolved in #329
