### ISSUE TITLE
"Currently working on" status

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#6]
A spot for every person to fill in a “current status” to describe what they’re “currently working on”. This way, you’ll be able to see at a glance what everyone is working on.

**Comment by lpatmo** [comment]
We've got this function working. :)

The user has to click out of the textarea (anywhere else on the page) for the status to show up, though. 

Anyone think this is confusing?

**Comment by Luxisapex** [comment]
I don't see it anywhere. Has it broken in the last 15 hours or am I misinterpreting something?

**Comment by lpatmo** [comment]
@Luxisapex It's in the `hangoutStatus` branch. Sorry for the confusion!

To switch between branches, you type `git checkout hangoutStatus` or `git checkout master` to switch back to master.

**Comment by Luxisapex** [comment]
RIght. So is it functioning? Then it makes sense to merge it imo, unless you would prefer to refine it first.

Big branches with long time between merging just creates issues in my experience.

**Comment by lpatmo** [comment]
It's working, but the hangout status icon that appears next to the text status still needs work, so I am holding off from merging it.
