### ISSUE TITLE
Restyle "kudos" section

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#60]
Instead of:

![screen shot 2016-03-17 at 1 21 27 am](https://cloud.githubusercontent.com/assets/4512699/13837154/9e1bdeb0-ebde-11e5-96ec-83331cf33b59.jpg)

... combine:
![image](https://cloud.githubusercontent.com/assets/4512699/13837145/895fa7f4-ebde-11e5-85fe-ba97e6efd57c.png)
Credit: @adachiu for the design

**Comment by distalx** [comment]
Have we decided on the type of search ?

**Comment by lpatmo** [comment]
@distalx Not yet! Search issue is sort of part of the tagging issue here: https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/34

Thanks for your PR! Have merged and am closing this issue now.
