### ISSUE TITLE
New Homepage View for Non-logged-In-Users

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#67]
The "Homepage for Non-logged-In-users" would emphasize **Slack community** + **Study hangouts**

Button **"Learn more here!"** re: Slack — This could open a new window to Slack's own site.
Buttons **"Join Us on Slack"** and **"Yes, I want to join CodeBuddies"** — After Slack registration, open up a brand new page that notifies users to do one of the following:
1) launch Slack chatroom link
2) open CB app to check out hangouts

If the Slack API doesn't let us redirect users after registering, @lpatmo suggests we can probably get the Slackbot to send a welcome message to new users that contains the 2 options.

Things that still need work on this homepage:
- Edit the text for the silent hangout so it aligns better (too long at the moment).
- Design a CB logo

_(btw, the logged-in view needs some stylistic edits to match this new homepage view, dash, and about)_

Zeplin link: https://zpl.io/5qd4v
What are your thoughts?

![home](https://cloud.githubusercontent.com/assets/13413986/13871826/d6bf3b76-eca2-11e5-88f6-fd439be10301.jpg)

Popup for "psst... Check out some hangout tips here!"
![screen shot 2016-03-18 at 12 24 33 am](https://cloud.githubusercontent.com/assets/13413986/13871188/f2b09242-ec9f-11e5-8389-335a60266cc8.png)

http://getemoji.com/

The hangout tips could be in the FAQ too. Then we could remove it from the homepage.

**Comment by sergeant-q** [comment]
This is pretty **awesome**! This is exactly the type of call to action I was looking for when it came to joining our slack room!  Good job @adachiu !
