### ISSUE TITLE
Implement a search box

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#68]
Mockup:

![screen shot 2016-03-19 at 12 35 08 am](https://cloud.githubusercontent.com/assets/4512699/13896652/7ed1573c-ed6a-11e5-8eaf-a6b621bb49e1.jpg)

@distalx recommends the meteorhacks:search-source package: https://meteorhacks.com/implementing-an-instant-search-solution-with-meteor.html

**Comment by distalx** [comment]
I'm thinking about rolling out our own custom search, 
Currently I'm considering search 
by `hangout title`
by `tags` (if we use tags)
by `users `

Guys, Please do let me know your thoughts.

**Comment by sergeant-q** [comment]
@distalx I think all of those three search fields are valid options and make sense. Can always just start with those fields and then add additional as we find necessary.

**Comment by lpatmo** [comment]
I would also add `description` to the mix -- since likely there will be some keywords in the description not mentioned in the title. But at a minimum, would be good to search by `hangout title`. 

Thanks for taking this issue, @distalx!
