### ISSUE TITLE
Feature: Give users the ability to clone hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#70]
Oftentimes I'll want to schedule a recurring hangout; would be nice if I could click "Copy" and not have to re-fill-out the title and description.

**Comment by foxiae** [comment]
Could we implement a 'reoccuring' feature as well?

Say for example, a channel is going through a book and they meet weekly at x time. So they can just schedule one meeting and have it repeat for x amount of weeks - just like the functionality you have when creating calendar invites.

**Comment by lpatmo** [comment]
@William-R-Wilson Oops, Will, I started working on this bug while I was on the plane earlier today (while I didn't have any wifi) and created this pull request: https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/73. Feedback welcome!

The second part of the bug -- @foxiae's suggestion of giving users the ability to repeat a hangout X number of times weekly from the start -- I haven't tackled, though.

**Comment by leewaygroups** [comment]
So, my understanding is hangout can either be one-off or recurring.

**Comment by leewaygroups** [comment]
Would it make sense if recurring hangout schedule is made more flexible such that the user can pick the days on which the hangout will reoccur?

More like: Time: 12PM - 1PM and days: date1, date2, ... daten.

**Comment by leewaygroups** [comment]
@lpatmo Is this feature (repeating hangouts) still needed?

**Comment by distalx** [comment]
@lpatmo  is this issue has been resolved in PR #73  ?
