### ISSUE TITLE
When deleting a hangout, user get's a 500 Error if button "Yes delete" is clicked more than once.

### ISSUE THREAD

**Issue by leewaygroups** [codebuddiesdotorg/cb-v2-scratch#91]
![cb_issue](https://cloud.githubusercontent.com/assets/7301892/14190423/ee15704a-f7bc-11e5-942e-89e94ec74cfb.png)

**Comment by sergeant-q** [comment]
I'll take a look at this! thanks for testing @leewaygroups

**Comment by sergeant-q** [comment]
This issue has now been fixed per this commit https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/93/commits/6f729562e061f811f46684d88d328a9e459558ef

Waiting on pull request https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/93 to be approved and merged.

**Comment by sergeant-q** [comment]
PR merged. Closing issue
