### ISSUE TITLE
Allow logged out users (non-members) ability to view scheduled hangouts

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/cb-v2-scratch#92]
I came across this bug while fixing issue #91. Someone can look up a hangout via the **console** by doing  a **mongo query** and grabbing the `id` of the hangout and going to the url ```hangout/:id``` even if you are not signed via Slack.

We need to restrict the **hangout details page** to _only_ logged in users.

**Comment by lpatmo** [comment]
I don't think is a bug (it's a feature! :)) -- currently on hangouts.codebuddies.org we link to the individual posts when we want to share them, so that non-members can hear about it and sign up for the hangout if they're interested. 

Let me know if this isn't what you're referring to.

**Comment by sergeant-q** [comment]
Yes! With the new **logged out** page we just implemented, users are not even able to see any new scheduled hangouts. I see your point in making it available to non-members though! Good point!

**Comment by lpatmo** [comment]
Good point... we might consider changing the home page later to populate some of the recent hangouts. At the moment, it's pretty good that the individual hangout links are public, IMO; those are the links most likely to be shared when someone wants to spread the word about a particular hangout.

@adachiu already started running usability tests, and we have some ideas for updating the home page even more.

**Comment by sergeant-q** [comment]
@lpatmo @adachiu I believe this is a non-issue correct? We agreed to keep the single hangout post pages public but users must login in order to RSVP or leave a comment.  Close?

**Comment by adachiu** [comment]
@sergeant-q Yup! Closing.
